// <auto-generated />

using GreetingsPorts.EntityGateway;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

namespace Greetings_SqliteMigrations.Migrations
{
    [DbContext(typeof(GreetingsEntityGateway))]
    [Migration("20210902180249_Initial")]
    partial class SqliteInitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.9");

            modelBuilder.Entity("GreetingsEntities.Greeting", b =>
                {
                    b.Property<int>("_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("Recipient_id")
                        .HasColumnType("INTEGER");

                    b.HasKey("_id");

                    b.HasIndex("Recipient_id");

                    b.ToTable("Greeting");
                });

            modelBuilder.Entity("GreetingsEntities.Person", b =>
                {
                    b.Property<int>("_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("TimeStamp")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("BLOB");

                    b.HasKey("_id");

                    b.HasAlternateKey("Name");

                    b.ToTable("People");
                });

            modelBuilder.Entity("GreetingsEntities.Greeting", b =>
                {
                    b.HasOne("GreetingsEntities.Person", "Recipient")
                        .WithMany("Greetings")
                        .HasForeignKey("Recipient_id");

                    b.Navigation("Recipient");
                });

            modelBuilder.Entity("GreetingsEntities.Person", b =>
                {
                    b.Navigation("Greetings");
                });
#pragma warning restore 612, 618
        }
    }
}
