// <auto-generated>
// This file was created to support generated messaging gateway tests.
// Unlike the Generated/ directory files, this provider is hand-written
// but follows the pattern established by RmqClassicMessageGatewayProvider.
// </auto-generated>

using System;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Threading;
using System.Threading.Tasks;
using Paramore.Brighter.MessagingGateway.Postgres;
using Paramore.Brighter.PostgresSQL.Tests.MessagingGateway.Proactor;
using Paramore.Brighter.PostgresSQL.Tests.MessagingGateway.Reactor;
using Paramore.Brighter.PostgresSQL.Tests.TestDoubles;

namespace Paramore.Brighter.PostgresSQL.Tests.MessagingGateway;

public class PostgresMessageGatewayProvider
    : IAmAMessageGatewayProactorProvider,
        IAmAMessageGatewayReactorProvider
{
    private readonly PostgresMessagingGatewayConnection _connection;
    private readonly RelationalDatabaseConfiguration _configuration;

    public PostgresMessageGatewayProvider()
    {
        var testHelper = new PostgresSqlTestHelper();
        testHelper.SetupDatabase();
        _configuration = testHelper.Configuration;
        _connection = new PostgresMessagingGatewayConnection(_configuration);
    }

    public void CleanUp(
        IAmAMessageProducerSync? producer,
        IAmAChannelSync? channel,
        IEnumerable<Message> messages
    )
    {
        if (channel != null)
        {
            channel.Purge();
            channel.Dispose();
        }

        producer?.Dispose();
    }

    public async Task CleanUpAsync(
        IAmAMessageProducerAsync? producer,
        IAmAChannelAsync? channel,
        IEnumerable<Message> messages
    )
    {
        if (channel != null)
        {
            await channel.PurgeAsync();
            channel.Dispose();
        }

        if (producer != null)
        {
            await producer.DisposeAsync();
        }
    }

    public IAmAChannelSync CreateChannel(PostgresSubscription subscription)
    {
        var channel = new PostgresChannelFactory(_connection).CreateSyncChannel(subscription);

        if (subscription.DeadLetterRoutingKey != null && subscription.RequeueCount > 0)
        {
            return new RequeueTrackingChannelSync(channel, subscription.RequeueCount);
        }

        return channel;
    }

    public async Task<IAmAChannelAsync> CreateChannelAsync(
        PostgresSubscription subscription,
        CancellationToken cancellationToken = default
    )
    {
        var channel = await new PostgresChannelFactory(_connection)
            .CreateAsyncChannelAsync(subscription, cancellationToken);

        if (subscription.DeadLetterRoutingKey != null && subscription.RequeueCount > 0)
        {
            return new RequeueTrackingChannelAsync(channel, subscription.RequeueCount);
        }

        return channel;
    }

    public IAmAMessageProducerSync CreateProducer(PostgresPublication publication)
    {
        var producers = new PostgresMessageProducerFactory(_connection, [publication]).Create();
        var producer = producers.First().Value;
        return (IAmAMessageProducerSync)producer;
    }

    public async Task<IAmAMessageProducerAsync> CreateProducerAsync(
        PostgresPublication publication,
        CancellationToken cancellationToken = default
    )
    {
        var producers = await new PostgresMessageProducerFactory(_connection, [publication])
            .CreateAsync();
        var producer = producers.First().Value;
        return (IAmAMessageProducerAsync)producer;
    }

    public PostgresPublication CreatePublication(RoutingKey routingKey, OnMissingChannel makeChannels = OnMissingChannel.Create)
    {
        return new PostgresPublication
        {
            Topic = routingKey,
            MakeChannels = makeChannels,
        };
    }

    public PostgresSubscription CreateSubscription(
        RoutingKey routingKey,
        ChannelName channelName,
        OnMissingChannel makeChannel,
        bool setupDeadLetterQueue = false
    )
    {
        // In PostgreSQL messaging, the producer writes to "queue" = Topic.Value and the consumer
        // reads from "queue" = ChannelName.Value, so they must match for message delivery.
        var pgChannelName = new ChannelName(routingKey.Value);

        if (setupDeadLetterQueue)
        {
            return new PostgresSubscription<MyCommand>(
                subscriptionName: new SubscriptionName(Uuid.NewAsString()),
                channelName: pgChannelName,
                routingKey: routingKey,
                messagePumpType: MessagePumpType.Proactor,
                makeChannels: makeChannel,
                deadLetterRoutingKey: new RoutingKey($"{routingKey}.DLQ"),
                requeueCount: 3
            );
        }

        return new PostgresSubscription<MyCommand>(
            subscriptionName: new SubscriptionName(Uuid.NewAsString()),
            channelName: pgChannelName,
            routingKey: routingKey,
            messagePumpType: MessagePumpType.Proactor,
            makeChannels: makeChannel
        );
    }

    public ChannelName GetOrCreateChannelName([CallerMemberName] string? testName = null)
    {
        return new ChannelName($"Queue{Uuid.New():N}");
    }

    public RoutingKey GetOrCreateRoutingKey([CallerMemberName] string? testName = null)
    {
        return new RoutingKey($"Topic{Uuid.New():N}");
    }

    public Message GetMessageFromDeadLetterQueue(PostgresSubscription subscription)
    {
        var dlqSubscription = new PostgresSubscription<MyCommand>(
            subscriptionName: new SubscriptionName(Uuid.NewAsString()),
            channelName: new ChannelName($"DLQ-{Uuid.New():N}"),
            routingKey: subscription.DeadLetterRoutingKey!,
            messagePumpType: MessagePumpType.Reactor,
            makeChannels: OnMissingChannel.Assume
        );

        var dlqConsumer = new PostgresMessageConsumer(
            _configuration,
            dlqSubscription
        );

        try
        {
            for (var i = 0; i < 10; i++)
            {
                var messages = dlqConsumer.Receive(TimeSpan.FromSeconds(5));
                var message = messages.First();
                if (message.Header.MessageType != MessageType.MT_NONE)
                {
                    dlqConsumer.Acknowledge(message);
                    return message;
                }
                Thread.Sleep(1000);
            }

            return new Message();
        }
        finally
        {
            dlqConsumer.Dispose();
        }
    }

    public async Task<Message> GetMessageFromDeadLetterQueueAsync(
        PostgresSubscription subscription,
        CancellationToken cancellationToken = default
    )
    {
        var dlqSubscription = new PostgresSubscription<MyCommand>(
            subscriptionName: new SubscriptionName(Uuid.NewAsString()),
            channelName: new ChannelName($"DLQ-{Uuid.New():N}"),
            routingKey: subscription.DeadLetterRoutingKey!,
            messagePumpType: MessagePumpType.Proactor,
            makeChannels: OnMissingChannel.Assume
        );

        var dlqConsumer = new PostgresMessageConsumer(
            _configuration,
            dlqSubscription
        );

        try
        {
            for (var i = 0; i < 10; i++)
            {
                var messages = await dlqConsumer.ReceiveAsync(TimeSpan.FromSeconds(5), cancellationToken);
                var message = messages.First();
                if (message.Header.MessageType != MessageType.MT_NONE)
                {
                    await dlqConsumer.AcknowledgeAsync(message, cancellationToken);
                    return message;
                }
                await Task.Delay(1000, cancellationToken);
            }

            return new Message();
        }
        finally
        {
            await dlqConsumer.DisposeAsync();
        }
    }

    private class RequeueTrackingChannelAsync : IAmAChannelAsync
    {
        private readonly IAmAChannelAsync _inner;
        private readonly int _maxRequeueCount;
        private readonly Dictionary<string, int> _requeueCounts = new();

        public RequeueTrackingChannelAsync(IAmAChannelAsync inner, int maxRequeueCount)
        {
            _inner = inner;
            _maxRequeueCount = maxRequeueCount;
        }

        public ChannelName Name => _inner.Name;
        public RoutingKey RoutingKey => _inner.RoutingKey;
        public void Enqueue(params Message[] messages) => _inner.Enqueue(messages);
        public void Stop(RoutingKey topic) => _inner.Stop(topic);
        public void Dispose() => _inner.Dispose();

        public Task AcknowledgeAsync(Message message, CancellationToken cancellationToken = default)
            => _inner.AcknowledgeAsync(message, cancellationToken);

        public Task PurgeAsync(CancellationToken cancellationToken = default)
            => _inner.PurgeAsync(cancellationToken);

        public Task<Message> ReceiveAsync(TimeSpan? timeout, CancellationToken cancellationToken = default)
            => _inner.ReceiveAsync(timeout, cancellationToken);

        public Task<bool> RejectAsync(Message message, MessageRejectionReason? reason = null, CancellationToken cancellationToken = default)
            => _inner.RejectAsync(message, reason, cancellationToken);

        public Task NackAsync(Message message, CancellationToken cancellationToken = default)
            => _inner.NackAsync(message, cancellationToken);

        public async Task<bool> RequeueAsync(Message message, TimeSpan? timeOut = null, CancellationToken cancellationToken = default)
        {
            var originalId = GetOriginalMessageId(message);

            _requeueCounts.TryGetValue(originalId, out var count);
            count++;
            _requeueCounts[originalId] = count;

            if (count >= _maxRequeueCount)
            {
                await _inner.RejectAsync(message, cancellationToken: cancellationToken);
                return false;
            }

            return await _inner.RequeueAsync(message, timeOut, cancellationToken);
        }

        private static string GetOriginalMessageId(Message message)
        {
            return message.Header.Bag.TryGetValue(Message.OriginalMessageIdHeaderName, out var id)
                ? id?.ToString() ?? message.Header.MessageId.ToString()
                : message.Header.MessageId.ToString();
        }
    }

    private class RequeueTrackingChannelSync : IAmAChannelSync
    {
        private readonly IAmAChannelSync _inner;
        private readonly int _maxRequeueCount;
        private readonly Dictionary<string, int> _requeueCounts = new();

        public RequeueTrackingChannelSync(IAmAChannelSync inner, int maxRequeueCount)
        {
            _inner = inner;
            _maxRequeueCount = maxRequeueCount;
        }

        public ChannelName Name => _inner.Name;
        public RoutingKey RoutingKey => _inner.RoutingKey;
        public void Enqueue(params Message[] messages) => _inner.Enqueue(messages);
        public void Stop(RoutingKey topic) => _inner.Stop(topic);
        public void Dispose() => _inner.Dispose();

        public void Acknowledge(Message message) => _inner.Acknowledge(message);
        public void Purge() => _inner.Purge();
        public Message Receive(TimeSpan? timeout) => _inner.Receive(timeout);

        public bool Reject(Message message, MessageRejectionReason? reason = null)
            => _inner.Reject(message, reason);

        public void Nack(Message message) => _inner.Nack(message);

        public bool Requeue(Message message, TimeSpan? timeOut = null)
        {
            var originalId = GetOriginalMessageId(message);

            _requeueCounts.TryGetValue(originalId, out var count);
            count++;
            _requeueCounts[originalId] = count;

            if (count >= _maxRequeueCount)
            {
                _inner.Reject(message);
                return false;
            }

            return _inner.Requeue(message, timeOut);
        }

        private static string GetOriginalMessageId(Message message)
        {
            return message.Header.Bag.TryGetValue(Message.OriginalMessageIdHeaderName, out var id)
                ? id?.ToString() ?? message.Header.MessageId.ToString()
                : message.Header.MessageId.ToString();
        }
    }
}
