#region Licence

/* The MIT License (MIT)
Copyright © 2014 Ian Cooper <ian_hammond_cooper@yahoo.co.uk>

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE. */

#endregion

// <auto-generated>
// This file is auto-generated by Paramore.Brighter.Test.Generator
// </auto-generated>

using System;
using System.Net.Mime;

using Paramore.Brighter.Observability;

namespace Paramore.Brighter.DynamoDB.Tests;

/// <summary>
/// Default implementation of <see cref="IAmAMessageFactory"/> that creates messages with randomly generated test data.
/// </summary>
public class DefaultMessageFactory : IAmAMessageFactory
{
    /// <summary>
    /// Creates a new message instance with randomly generated header values and body content for testing purposes.
    /// </summary>
    /// <param name="timestamp">The timestamp for the message. If null, the current UTC time will be used.</param>
    /// <returns>A new <see cref="Message"/> instance with randomly generated test data.</returns>
    public Message Create(DateTimeOffset? timestamp = null)
    {
        var messageHeader = new MessageHeader(
            messageId: Id.Random(),
            topic: new RoutingKey(Uuid.NewAsString()),
            messageType: MessageType.MT_DOCUMENT,
            source: new Uri(Uuid.NewAsString(), UriKind.Relative),
            type: new CloudEventsType(Uuid.NewAsString()),
            timeStamp: timestamp ?? DateTimeOffset.UtcNow,
            correlationId: Id.Random(),
            replyTo: new RoutingKey(Uuid.NewAsString()),
            contentType: new ContentType(MediaTypeNames.Text.Plain),
            partitionKey: Uuid.NewAsString(),
            dataSchema: new Uri("https://schema.test"),
            subject: Uuid.NewAsString(),
            delayed: TimeSpan.FromMilliseconds(5),
            traceParent: "00-abcdef0123456789-abcdef0123456789-01",
            traceState: "state123",
            baggage: new Baggage(),
            workflowId: Id.Random(),
            jobId: Id.Random());

        messageHeader.Bag.Add("header1", Uuid.NewAsString());
        messageHeader.Bag.Add("header2", Uuid.NewAsString());
        messageHeader.Bag.Add("header3", Uuid.NewAsString());
        messageHeader.Bag.Add("header4", Uuid.NewAsString());
        messageHeader.Bag.Add("header5", Uuid.NewAsString());

        return new Message(messageHeader, new MessageBody(Uuid.NewAsString()));
    }
}