version: '3'

services:
  eventstore:
    image: eventstore/eventstore
    ports:
      - "1113:1113" # TCP (default 1113)
      - "2113:2113" # HTTP (default 2113)
    volumes:
      - eventstore-data:/var/lib/eventstore
    environment:
      - EVENTSTORE_RUN_PROJECTIONS=ALL
      - EVENTSTORE_START_STANDARD_PROJECTIONS=TRUE
      - EVENTSTORE_INSECURE=true
      - EVENTSTORE_DEV=true
    
volumes:
  eventstore-data:
    driver: local
  