version: '3'

services:
  rabbitmq:
    image: brightercommand/rabbitmq:3.13-management-delay
    platform: linux/amd64
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq-home:/var/lib/rabbitmq

volumes:
  rabbitmq-home:
    driver: local
  