version: '3'

services:
  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "6831:6831/udp" # UDP port for Jaeger agent
      - "16686:16686" # Web UI
      - "14250:14250" # gRPC port for Jaeger agent
      - "14268:14268" # HTTP port for spans