// <auto-generated />

using System;
using GreetingsPorts.EntityGateway;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

namespace Greetings_MySqlMigrations.Migrations
{
    [DbContext(typeof(GreetingsEntityGateway))]
    [Migration("20210920201732_InitialCreate")]
    partial class MySqlInitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.9");

            modelBuilder.Entity("GreetingsEntities.Greeting", b =>
                {
                    b.Property<int>("_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int?>("Recipient_id")
                        .HasColumnType("int");

                    b.HasKey("_id");

                    b.HasIndex("Recipient_id");

                    b.ToTable("Greeting");
                });

            modelBuilder.Entity("GreetingsEntities.Person", b =>
                {
                    b.Property<int>("_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime?>("TimeStamp")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp(6)");

                    b.HasKey("_id");

                    b.HasAlternateKey("Name");

                    b.ToTable("People");
                });

            modelBuilder.Entity("GreetingsEntities.Greeting", b =>
                {
                    b.HasOne("GreetingsEntities.Person", "Recipient")
                        .WithMany("Greetings")
                        .HasForeignKey("Recipient_id");

                    b.Navigation("Recipient");
                });

            modelBuilder.Entity("GreetingsEntities.Person", b =>
                {
                    b.Navigation("Greetings");
                });
#pragma warning restore 612, 618
        }
    }
}
