// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SalutationApp.EntityGateway;

namespace Salutations_MySqlMigrations.Migrations
{
    [DbContext(typeof(SalutationsEntityGateway))]
    [Migration("20220202081313_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.13");

            modelBuilder.Entity("SalutationEntities.Salutation", b =>
                {
                    b.Property<int>("_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Greeting")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<byte[]>("TimeStamp")
                        .HasColumnType("longblob");

                    b.HasKey("_id");

                    b.ToTable("Salutations");
                });
#pragma warning restore 612, 618
        }
    }
}
