#region Licence

/* The MIT License (MIT)
Copyright © 2014 Ian Cooper <ian_hammond_cooper@yahoo.co.uk>

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE. */

#endregion

using System;
using System.IO;
using System.Linq;
using System.Text.Json;
using System.Threading.Tasks;
using Microsoft.Extensions.Logging;
using Paramore.Brighter.Test.Generator.Configuration;
using Xunit;

namespace Paramore.Brighter.Test.Generator.Tests.GeneratedFileAudit;

/// <summary>
/// A scan over a tree passes trivially when it finds nothing to look at, so the audit that guards
/// the repository has to be shown catching something. These canaries generate a small tree with
/// the real generators, then break it in each of the two ways the audit exists to notice.
/// </summary>
public class AuditCanaryTests : IDisposable
{
    private const string GATEWAY_NAME = "Sample";

    private static readonly string SAMPLE_CONFIGURATION =
        $$"""
          {
            "Namespace": "Sample.Tests",
            "MessagingGateways": {
              "{{GATEWAY_NAME}}": {
                "Publication": "Sample.SamplePublication",
                "Subscription": "Sample.SampleSubscription",
                "MessageGatewayProvider": "Sample.Tests.SampleMessageGatewayProvider",
                "Category": "Sample",
                "CollectionName": "Sample"
              }
            },
            "Outboxes": {
              "{{GATEWAY_NAME}}": {
                "Transaction": "System.Data.Common.DbTransaction",
                "OutboxProvider": "SampleOutboxProvider",
                "Category": "Sample",
                "CollectionName": "SampleOutbox"
              }
            }
          }
          """;

    private readonly string _root;
    private readonly string _testsRoot;
    private readonly string _projectFolder;

    public AuditCanaryTests()
    {
        _root = Path.Combine(Path.GetTempPath(), $"GeneratedFileAudit_{Guid.NewGuid()}");
        _testsRoot = Path.Combine(_root, "tests");
        _projectFolder = Path.Combine(_testsRoot, "Sample.Tests");
        Directory.CreateDirectory(_projectFolder);
        File.WriteAllText(Path.Combine(_projectFolder, "test-configuration.json"), SAMPLE_CONFIGURATION);
    }

    [Fact]
    public async Task When_a_file_the_generator_would_not_write_is_planted_should_report_an_orphan()
    {
        // Arrange - a tree the generators have just written, which the audit agrees with
        await GenerateAsync();
        Assert.Empty(new GeneratedTreeAudit(_testsRoot).Orphans);

        // Act - a file no template produces, in a directory the generator owns
        var planted = Path.Combine(_projectFolder, "MessagingGateway", GATEWAY_NAME, "Generated",
            "Reactor", "When_no_template_produces_this_should_be_reported.cs");
        File.WriteAllText(planted, "// hand-written, under an <auto-generated> roof");
        var audit = new GeneratedTreeAudit(_testsRoot);

        // Assert - the planted file, and only it, is reported
        Assert.Equal([planted], audit.Orphans);
        Assert.Empty(audit.Missing);
    }

    [Fact]
    public async Task When_a_file_the_generator_would_write_is_deleted_should_report_it_missing()
    {
        // Arrange - a tree the generators have just written, which the audit agrees with
        await GenerateAsync();
        Assert.Empty(new GeneratedTreeAudit(_testsRoot).Missing);

        // Act - one generated file goes away, as a dropped generation code path would leave it
        var deleted = Directory
            .EnumerateFiles(Path.Combine(_projectFolder, "Outbox", GATEWAY_NAME, "Generated", "Sync"), "*.cs")
            .OrderBy(file => file, StringComparer.Ordinal)
            .First();
        File.Delete(deleted);
        var audit = new GeneratedTreeAudit(_testsRoot);

        // Assert - the deleted file, and only it, is reported
        Assert.Equal([deleted], audit.Missing);
        Assert.Empty(audit.Orphans);
    }

    private async Task GenerateAsync()
    {
        var factory = LoggerFactory.Create(builder => builder.AddConsole());
        var configuration = JsonSerializer.Deserialize<TestConfiguration>(
            File.ReadAllText(Path.Combine(_projectFolder, "test-configuration.json")))!;
        configuration.DestinationFolder = _projectFolder;

        await new Generators.OutboxGenerator(factory.CreateLogger<Generators.OutboxGenerator>())
            .GenerateAsync(configuration);
        await new Generators.MessagingGatewayGenerator(factory.CreateLogger<Generators.MessagingGatewayGenerator>())
            .GenerateAsync(configuration);
    }

    public void Dispose()
    {
        if (Directory.Exists(_root))
        {
            Directory.Delete(_root, recursive: true);
        }

        GC.SuppressFinalize(this);
    }
}
