// <auto-generated>
// This file is auto-generated by Paramore.Brighter.Test.Generator
// </auto-generated>

using System;

namespace Paramore.Brighter.PostgresSQL.Tests;

/// <summary>
/// Factory for creating message instances with optional timestamps.
/// </summary>
public interface IAmAMessageFactory
{
    /// <summary>
    /// Creates a new message instance.
    /// </summary>
    /// <param name="timestamp">The timestamp for the message. If null, the current time will be used.</param>
    /// <returns>A new <see cref="Message"/> instance.</returns>
    Message Create(DateTimeOffset? timestamp = null);
}
