# You need to downoad the dockerfiles from the GitHub directory, switch to using RMQ 2.8.7, and change tag
# to 2.8.0 and then build locally
FROM bijukunjummen/rabbitmq-server:2.8.0

COPY rabbitmq.config /etc/rabbitmq/