#region Licence

/* The MIT License (MIT)
Copyright © 2014 Ian Cooper <ian_hammond_cooper@yahoo.co.uk>

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE. */

#endregion

// <auto-generated>
// This file is auto-generated by Paramore.Brighter.Test.Generator
// </auto-generated>
using System;
using System.Collections.Generic;
using System.Net.Mime;
using System.Text;

using Paramore.Brighter.Observability;

namespace Paramore.Brighter.DynamoDB.V4.Tests;

/// <summary>
/// Default implementation of <see cref="IAmAMessageBuilder"/> that creates messages with randomly generated test data.
/// </summary>
public class DefaultMessageBuilder : IAmAMessageBuilder
{
    private Dictionary<string, object> _bag = new()
    {
        ["header1"] = Uuid.NewAsString(),
        ["header2"] = Uuid.NewAsString(),
        ["header3"] = Uuid.NewAsString(),
        ["header4"] = Uuid.NewAsString(),
        ["header5"] = Uuid.NewAsString()
    };
    private Baggage _baggage = new();
    private ContentType _contentType = new ContentType(MediaTypeNames.Text.Plain);
    private Id _correlationId = Id.Random();
    private Uri? _dataSchema = new Uri($"https://{Uuid.New():N}.test");
    private string? _dataRef = Uuid.NewAsString();
    private TimeSpan? _delayed;
    private Id? _jobId = Id.Random();
    private Id? _messageId = Id.Random();
    private MessageType _messageType = MessageType.MT_EVENT;
    private PartitionKey _partitionKey = new PartitionKey(Uuid.NewAsString());
    private RoutingKey? _replyTo = new RoutingKey(Uuid.NewAsString());
    private string? _subject = Uuid.NewAsString();
    private string? _specVersion = "1.0";
    private Uri? _source = new Uri(Uuid.NewAsString(), UriKind.Relative);
    private RoutingKey _topic = new RoutingKey(Uuid.NewAsString());
    private DateTimeOffset _timeStamp = DateTimeOffset.UtcNow;
    private TraceParent? _traceParent = new TraceParent(Uuid.NewAsString());
    private TraceState? _traceState = new TraceState(Uuid.NewAsString());
    private CloudEventsType _type = new CloudEventsType(Uuid.NewAsString());
    private Id? _workflowId = Id.Random();
    private byte[] _body = Encoding.UTF8.GetBytes(Uuid.NewAsString());

    /// <inheritdoc />
    public IAmAMessageBuilder SetBag(Dictionary<string, object> bag)
    {
        _bag = bag;
        return this;
    }

    /// <inheritdoc />
    public IAmAMessageBuilder SetBaggage(Baggage baggage)
    {
        _baggage = baggage;
        return this;
    }

    /// <inheritdoc />
    public IAmAMessageBuilder SetContentType(ContentType contentType)
    {
        _contentType = contentType;
        return this;
    }

    /// <inheritdoc />
    public IAmAMessageBuilder SetCorrelationId(Id correlationId)
    {
        _correlationId = correlationId;
        return this;
    }

    /// <inheritdoc />
    public IAmAMessageBuilder SetDataSchema(Uri? dataSchema)
    {
        _dataSchema = dataSchema;
        return this;
    }

    /// <inheritdoc />
    public IAmAMessageBuilder SetDataRef(string? dataRef)
    {
        _dataRef = dataRef;
        return this;
    }

    /// <inheritdoc />
    public IAmAMessageBuilder SetDelayed(TimeSpan? delayed)
    {
        _delayed = delayed;
        return this;
    }

    /// <inheritdoc />
    public IAmAMessageBuilder SetJobId(Id? jobId)
    {
        _jobId = jobId;
        return this;
    }

    /// <inheritdoc />
    public IAmAMessageBuilder SetMessageId(Id? messageId)
    {
        _messageId = messageId;
        return this;
    }

    /// <inheritdoc />
    public IAmAMessageBuilder SetMessageType(MessageType messageType)
    {
        _messageType = messageType;
        return this;
    }

    /// <inheritdoc />
    public IAmAMessageBuilder SetPartitionKey(PartitionKey partitionKey)
    {
        _partitionKey = partitionKey;
        return this;
    }

    /// <inheritdoc />
    public IAmAMessageBuilder SetReplyTo(RoutingKey? replyTo)
    {
        _replyTo = replyTo;
        return this;
    }

    /// <inheritdoc />
    public IAmAMessageBuilder SetSubject(string? subject)
    {
        _subject = subject;
        return this;
    }

    /// <inheritdoc />
    public IAmAMessageBuilder SetSpecVersion(string? specVersion)
    {
        _specVersion = specVersion;
        return this;
    }

    /// <inheritdoc />
    public IAmAMessageBuilder SetSource(Uri? source)
    {
        _source = source;
        return this;
    }

    /// <inheritdoc />
    public IAmAMessageBuilder SetTopic(RoutingKey topic)
    {
        _topic = topic;
        return this;
    }

    /// <inheritdoc />
    public IAmAMessageBuilder SetTimeStamp(DateTimeOffset timeStamp)
    {
        _timeStamp = timeStamp;
        return this;
    }

    /// <inheritdoc />
    public IAmAMessageBuilder SetTraceParent(TraceParent? traceParent)
    {
        _traceParent = traceParent;
        return this;
    }

    /// <inheritdoc />
    public IAmAMessageBuilder SetTraceState(TraceState? traceState)
    {
        _traceState = traceState;
        return this;
    }

    /// <inheritdoc />
    public IAmAMessageBuilder SetType(CloudEventsType type)
    {
        _type = type;
        return this;
    }

    /// <inheritdoc />
    public IAmAMessageBuilder SetWorkflowId(Id? workflowId)
    {
        _workflowId = workflowId;
        return this;
    }

    /// <inheritdoc />
    public IAmAMessageBuilder SetBody(byte[] body)
    {
        _body = body;
        return this;
    }

    /// <inheritdoc />
    public Message Build()
    {
        var messageHeader = new MessageHeader(
            messageId: _messageId,
            topic: _topic,
            messageType: _messageType,
            source: _source,
            type: _type,
            timeStamp: _timeStamp,
            correlationId: _correlationId,
            replyTo: _replyTo,
            contentType: _contentType,
            partitionKey: _partitionKey,
            subject: _subject,
            dataSchema: _dataSchema,
            delayed: _delayed,
            traceParent: _traceParent,
            traceState: _traceState,
            baggage: _baggage,
            workflowId: _workflowId,
            jobId: _jobId)
        {
            SpecVersion = _specVersion, 
            Bag = _bag
        };

        return new Message(messageHeader, new MessageBody(_body));
    }
}
