// The MIT License (MIT)
// Copyright © 2014 Ian Cooper <ian_hammond_cooper@yahoo.co.uk>
// 
// Permission is hereby granted, free of charge, to any person obtaining a copy
//  of this software and associated documentation files (the "Software"), to deal
//  in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
// 
//  The above copyright notice and this permission notice shall be included in
// all copies or substantial portions of the Software.
// 
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
// THE SOFTWARE.

using System.ComponentModel;

namespace Paramore.Brighter.Inbox.Oracle;

/// <summary>
/// Provides DDL statements for creating and checking the existence of an Inbox table in Oracle.
/// Requires Oracle 12c or later (uses identity columns and TIMESTAMP WITH TIME ZONE).
/// </summary>
public class OracleInboxBuilder
{
    private const string TextInboxDDL =
        """
        CREATE TABLE {0}
        (
            Id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            CommandId VARCHAR2(256 CHAR) NOT NULL,
            CommandType VARCHAR2(256 CHAR),
            CommandBody CLOB,
            Timestamp TIMESTAMP WITH TIME ZONE,
            ContextKey VARCHAR2(256 CHAR),
            CONSTRAINT UQ_{0}_Command_Context UNIQUE (CommandId, ContextKey) -- Optional: keeps the unique combo constraint if needed
        ); 
        """;

    private const string BinaryInboxDDL =
        """
        CREATE TABLE {0}
        (
            Id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            CommandId VARCHAR2(256 CHAR) NOT NULL,
            CommandType VARCHAR2(256 CHAR),
            CommandBody BLOB,
            Timestamp TIMESTAMP WITH TIME ZONE,
            ContextKey VARCHAR2(256 CHAR),
            CONSTRAINT UQ_{0}_Command_Context UNIQUE (CommandId, ContextKey) -- Optional: keeps the unique combo constraint if needed
        ); 
        """;

    private const string JsonInboxDDL =
        """
        CREATE TABLE {0}
        (
            Id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            CommandId VARCHAR2(256 CHAR) NOT NULL,
            CommandType VARCHAR2(256 CHAR),
            CommandBody BLOB,
            Timestamp TIMESTAMP WITH TIME ZONE,
            ContextKey VARCHAR2(256 CHAR),
            CONSTRAINT UQ_{0}_Command_Context UNIQUE (CommandId, ContextKey),
            CONSTRAINT ENSURE_{0}_JSON CHECK (CommandBody IS JSON)
        );
        """;

    private const string InboxExistsQuery =
        """
        SELECT COUNT(1)
        FROM ALL_TABLES
        WHERE OWNER = '{0}' 
          AND TABLE_NAME = '{1}';
        """;

    
    /// <summary>
    /// Gets the DDL statement required to create the Inbox table in Oracle.
    /// </summary>
    /// <param name="inboxTableName">The name to give the Inbox table.</param>
    /// <param name="binaryMessage">
    /// When <see langword="true"/>, the <c>CommandBody</c> column is created as <c>BLOB</c>.
    /// Ignored when <paramref name="jsonMessage"/> is <see langword="true"/>.
    /// </param>
    /// <param name="jsonMessage">
    /// When <see langword="true"/>, the <c>CommandBody</c> column is created as <c>BLOB</c>
    /// with an <c>IS JSON</c> check constraint. Requires Oracle 12c or later.
    /// Takes precedence over <paramref name="binaryMessage"/>.
    /// </param>
    /// <returns>A <c>CREATE TABLE</c> statement formatted with the given table name.</returns>
    public static string GetDDL(string inboxTableName, bool binaryMessage = false, bool jsonMessage = false)
    {
        if (jsonMessage)
        {
            return string.Format(JsonInboxDDL, inboxTableName);
        }

        if (binaryMessage)
        {
            return string.Format(BinaryInboxDDL, inboxTableName);
        }

        return string.Format(TextInboxDDL, inboxTableName);
    }

    /// <summary>
    /// Gets the SQL statement that checks whether the Inbox table already exists in the given schema.
    /// </summary>
    /// <param name="ownerName">The Oracle schema (owner) to search within.</param>
    /// <param name="inboxTableName">The table name to check.</param>
    /// <returns>A SQL query that returns 1 if the table exists, 0 otherwise.</returns>
    /// <exception cref="InvalidEnumArgumentException">Thrown when <paramref name="ownerName"/> or <paramref name="inboxTableName"/> is null or empty.</exception>
    public static string GetExistsQuery(string ownerName, string inboxTableName)
    {
        if (string.IsNullOrEmpty(ownerName) || string.IsNullOrEmpty(inboxTableName))
            throw new InvalidEnumArgumentException("You must provide a table schema and tablename for the inbox table");
        return string.Format(InboxExistsQuery, ownerName, inboxTableName);
    }
}
