// <auto-generated/>
// ─────────────────────────────────────────────────────────────────────────────────────
// PROTOTYPE — hand-written stand-in for what BrighterRegistrationsGenerator WOULD emit
// for the declaration in OrdersRegistrations.cs.
//
// Note what is NOT here: no builder calls, no open-generic casts, no default-mapper logic.
// The generator emits inert data; AddRegistrations (library code) does the thinking.
// [RegistrationGroup] conventions were evaluated at generation time against the discovered
// type names, so each group below is just another pre-filtered block of static data —
// the regex never runs at runtime.
// ─────────────────────────────────────────────────────────────────────────────────────
#nullable enable

namespace Orders.Domain
{
    public static partial class OrdersRegistrations
    {
        /// <summary>Every Brighter type discovered in this assembly.</summary>
        public static global::Paramore.Brighter.RegistrationCatalog Catalog { get; } = BuildCatalog();

        /// <summary>[RegistrationGroup("Billing", InNamespace = "Orders.Domain.Billing")]</summary>
        public static global::Paramore.Brighter.RegistrationCatalog Billing { get; } = BuildBilling();

        /// <summary>[RegistrationGroup("Fulfilment", InNamespace = "Orders.Domain.Fulfilment")]</summary>
        public static global::Paramore.Brighter.RegistrationCatalog Fulfilment { get; } = BuildFulfilment();

        /// <summary>[RegistrationGroup("Urgent", TypeNamePattern = "^Urgent")]</summary>
        public static global::Paramore.Brighter.RegistrationCatalog Urgent { get; } = BuildUrgent();

        private static global::Paramore.Brighter.RegistrationCatalog BuildCatalog()
        {
            var catalog = new global::Paramore.Brighter.RegistrationCatalog();
            catalog.AddHandler(typeof(global::Orders.Domain.Billing.ChargeCardHandler), typeof(global::Orders.Domain.Billing.ChargeCard), isAsync: false);
            catalog.AddHandler(typeof(global::Orders.Domain.Billing.RefundPaymentHandler), typeof(global::Orders.Domain.Billing.RefundPayment), isAsync: true);
            catalog.AddHandler(typeof(global::Orders.Domain.Billing.UrgentRefundHandler), typeof(global::Orders.Domain.Billing.UrgentRefund), isAsync: true);
            catalog.AddHandler(typeof(global::Orders.Domain.Fulfilment.ShipOrderHandler), typeof(global::Orders.Domain.Fulfilment.ShipOrder), isAsync: false);
            catalog.AddHandler(typeof(global::Orders.Domain.Fulfilment.UrgentShipOrderHandler), typeof(global::Orders.Domain.Fulfilment.UrgentShipOrder), isAsync: false);
            catalog.AddHandler(typeof(global::Orders.Domain.Notifications.ReceiptRequestedHandler), typeof(global::Orders.Domain.Notifications.ReceiptRequested), isAsync: true);
            catalog.AddMapper(typeof(global::Orders.Domain.Notifications.ReceiptRequestedMapper), typeof(global::Orders.Domain.Notifications.ReceiptRequested), isAsync: false);
            return catalog;
        }

        private static global::Paramore.Brighter.RegistrationCatalog BuildBilling()
        {
            var catalog = new global::Paramore.Brighter.RegistrationCatalog();
            catalog.AddHandler(typeof(global::Orders.Domain.Billing.ChargeCardHandler), typeof(global::Orders.Domain.Billing.ChargeCard), isAsync: false);
            catalog.AddHandler(typeof(global::Orders.Domain.Billing.RefundPaymentHandler), typeof(global::Orders.Domain.Billing.RefundPayment), isAsync: true);
            catalog.AddHandler(typeof(global::Orders.Domain.Billing.UrgentRefundHandler), typeof(global::Orders.Domain.Billing.UrgentRefund), isAsync: true);
            return catalog;
        }

        private static global::Paramore.Brighter.RegistrationCatalog BuildFulfilment()
        {
            var catalog = new global::Paramore.Brighter.RegistrationCatalog();
            catalog.AddHandler(typeof(global::Orders.Domain.Fulfilment.ShipOrderHandler), typeof(global::Orders.Domain.Fulfilment.ShipOrder), isAsync: false);
            catalog.AddHandler(typeof(global::Orders.Domain.Fulfilment.UrgentShipOrderHandler), typeof(global::Orders.Domain.Fulfilment.UrgentShipOrder), isAsync: false);
            return catalog;
        }

        private static global::Paramore.Brighter.RegistrationCatalog BuildUrgent()
        {
            var catalog = new global::Paramore.Brighter.RegistrationCatalog();
            catalog.AddHandler(typeof(global::Orders.Domain.Billing.UrgentRefundHandler), typeof(global::Orders.Domain.Billing.UrgentRefund), isAsync: true);
            catalog.AddHandler(typeof(global::Orders.Domain.Fulfilment.UrgentShipOrderHandler), typeof(global::Orders.Domain.Fulfilment.UrgentShipOrder), isAsync: false);
            return catalog;
        }
    }
}
