// The MIT License (MIT)
// Copyright © 2014 Ian Cooper <ian_hammond_cooper@yahoo.co.uk>
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
//  of this software and associated documentation files (the "Software"), to deal
//  in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
//
//  The above copyright notice and this permission notice shall be included in
// all copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
// THE SOFTWARE.

namespace Paramore.Brighter.Outbox.Oracle;

/// <summary>
/// Oracle-specific SQL queries for the Brighter Outbox.
/// Uses <c>OFFSET … ROWS FETCH NEXT … ROWS ONLY</c> for pagination (Oracle 12c+)
/// and named bind variables prefixed with <c>:</c>.
/// Parameter names are matched by name via <see cref="Oracle.ManagedDataAccess.Client.OracleCommand.BindByName"/>.
/// </summary>
public class OracleQueries : IRelationDatabaseOutboxQueries
{
    /// <inheritdoc />
    public string PagedDispatchedCommand { get; } =
        "SELECT * FROM {0} WHERE Dispatched IS NOT NULL AND Dispatched < :DispatchedSince " +
        "ORDER BY Timestamp DESC OFFSET :Skip ROWS FETCH NEXT :Take ROWS ONLY";

    /// <inheritdoc />
    public string PagedReadCommand { get; } =
        "SELECT * FROM {0} ORDER BY Timestamp ASC OFFSET :Skip ROWS FETCH NEXT :Take ROWS ONLY";

    /// <inheritdoc />
    public string PagedOutstandingCommand { get; } =
        "SELECT * FROM {0} WHERE Dispatched IS NULL AND Timestamp < :TimestampSince {1} " +
        "ORDER BY Timestamp DESC OFFSET :Skip ROWS FETCH NEXT :Take ROWS ONLY";

    /// <inheritdoc />
    public string PagedOutstandingCommandInStatement { get; } = "AND Topic NOT IN ( {0} )";

    /// <inheritdoc />
    public string AddCommand { get; } =
        "INSERT INTO {0} (MessageId,MessageType,Topic,Timestamp,CorrelationId,ReplyTo,ContentType,PartitionKey," +
        "HeaderBag,Body,Source,Type,DataSchema,Subject,TraceParent,TraceState,Baggage,WorkflowId,JobId) " +
        "VALUES (:MessageId,:MessageType,:Topic,:Timestamp,:CorrelationId,:ReplyTo,:ContentType,:PartitionKey," +
        ":HeaderBag,:Body,:Source,:Type,:DataSchema,:Subject,:TraceParent,:TraceState,:Baggage,:WorkflowId,:JobId)";

    /// <inheritdoc />
    /// <remarks>
    /// <c>{1}</c> is replaced with <c>SELECT :p0_… FROM DUAL UNION ALL SELECT :p1_… FROM DUAL</c>,
    /// generated by <see cref="OracleOutbox.GenerateBulkInsert"/>. Oracle does not support
    /// multi-row <c>VALUES</c> clauses before version 23c.
    /// </remarks>
    public string BulkAddCommand { get; } =
        "INSERT INTO {0} (MessageId,MessageType,Topic,Timestamp,CorrelationId,ReplyTo,ContentType,PartitionKey," +
        "HeaderBag,Body,Source,Type,DataSchema,Subject,TraceParent,TraceState,Baggage,WorkflowId,JobId) {1}";

    /// <inheritdoc />
    public string MarkDispatchedCommand { get; } =
        "UPDATE {0} SET Dispatched = :DispatchedAt WHERE MessageId = :MessageId";

    /// <inheritdoc />
    public string MarkMultipleDispatchedCommand { get; } =
        "UPDATE {0} SET Dispatched = :DispatchedAt WHERE MessageId IN ( {1} )";

    /// <inheritdoc />
    public string GetMessageCommand { get; } = "SELECT * FROM {0} WHERE MessageId = :MessageId";

    /// <inheritdoc />
    public string GetMessagesCommand { get; } =
        "SELECT * FROM {0} WHERE MessageId IN ( {1} ) ORDER BY Timestamp ASC";

    /// <inheritdoc />
    public string DeleteMessagesCommand { get; } = "DELETE FROM {0} WHERE MessageId IN ( {1} )";

    /// <inheritdoc />
    public string GetNumberOfOutstandingMessagesCommand { get; } =
        "SELECT COUNT(1) FROM {0} WHERE Dispatched IS NULL";
}
