// The MIT License (MIT)
// Copyright © 2014 Ian Cooper <ian_hammond_cooper@yahoo.co.uk>
// 
// Permission is hereby granted, free of charge, to any person obtaining a copy
//  of this software and associated documentation files (the "Software"), to deal
//  in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
// 
//  The above copyright notice and this permission notice shall be included in
// all copies or substantial portions of the Software.
// 
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
// THE SOFTWARE.

using System;

namespace Paramore.Brighter.Outbox.Oracle;

/// <summary>
/// Provides DDL statements for creating and checking the existence of an Outbox table in Oracle.
/// Requires Oracle 12c or later (uses identity columns and TIMESTAMP WITH TIME ZONE).
/// </summary>
public class OracleOutboxBuilder
{
    private const string TextOutboxDdl =
        """
        CREATE TABLE {0}
        (
            Id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            MessageId VARCHAR2(255 CHAR) UNIQUE NOT NULL,
            Topic VARCHAR2(255 CHAR),
            MessageType VARCHAR2(32 CHAR),
            Timestamp TIMESTAMP WITH TIME ZONE,
            CorrelationId VARCHAR2(255 CHAR),
            ReplyTo VARCHAR2(255 CHAR),
            ContentType VARCHAR2(128 CHAR),
            PartitionKey VARCHAR2(128 CHAR),  
            WorkflowId VARCHAR2(255 CHAR),
            JobId VARCHAR2(255 CHAR),
            Dispatched TIMESTAMP WITH TIME ZONE,
            HeaderBag CLOB,
            Body CLOB,
            Source VARCHAR2(255 CHAR),
            Type VARCHAR2(255 CHAR),
            DataSchema VARCHAR2(255 CHAR),
            Subject VARCHAR2(255 CHAR),
            TraceParent VARCHAR2(255 CHAR),
            TraceState VARCHAR2(255 CHAR),
            Baggage CLOB,
            DataRef VARCHAR2(255 CHAR),
            SpecVersion VARCHAR2(255 CHAR)
        ); 
        """;
    
    private const string BinaryOutboxDdl =
        """
        CREATE TABLE {0}
        (
            Id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            MessageId VARCHAR2(255 CHAR) UNIQUE NOT NULL,
            Topic VARCHAR2(255 CHAR),
            MessageType VARCHAR2(32 CHAR),
            Timestamp TIMESTAMP WITH TIME ZONE,
            CorrelationId VARCHAR2(255 CHAR),
            ReplyTo VARCHAR2(255 CHAR),
            ContentType VARCHAR2(128 CHAR),
            PartitionKey VARCHAR2(128 CHAR),  
            WorkflowId VARCHAR2(255 CHAR),
            JobId VARCHAR2(255 CHAR),
            Dispatched TIMESTAMP WITH TIME ZONE,
            HeaderBag CLOB,
            Body BLOB,
            Source VARCHAR2(255 CHAR),
            Type VARCHAR2(255 CHAR),
            DataSchema VARCHAR2(255 CHAR),
            Subject VARCHAR2(255 CHAR),
            TraceParent VARCHAR2(255 CHAR),
            TraceState VARCHAR2(255 CHAR),
            Baggage CLOB,
            DataRef VARCHAR2(255 CHAR),
            SpecVersion VARCHAR2(255 CHAR)
        ); 
        """;

    private const string OutboxExistsSql = 
        """
        SELECT COUNT(1)
        FROM ALL_TABLES
        WHERE OWNER = '{0}' 
          AND TABLE_NAME = '{1}';
        """;
    
    /// <summary>
    /// Gets the SQL statement that checks whether the Outbox table already exists in the given schema.
    /// </summary>
    /// <param name="outboxTable">The table name to check.</param>
    /// <param name="ownerName">The Oracle schema (owner) to search within.</param>
    /// <returns>A SQL query that returns 1 if the table exists, 0 otherwise.</returns>
    public static string GetExistsQuery(string outboxTable, string ownerName)
    {
        return string.Format(OutboxExistsSql, outboxTable, ownerName);
    }

    /// <summary>
    /// Gets the DDL statement required to create the Outbox table in Oracle.
    /// </summary>
    /// <param name="outboxTableName">The name to give the Outbox table.</param>
    /// <param name="hasBinaryMessagePayload">
    /// When <see langword="true"/>, the <c>Body</c> column is created as <c>BLOB</c>;
    /// otherwise it is created as <c>CLOB</c>.
    /// </param>
    /// <returns>A <c>CREATE TABLE</c> statement formatted with the given table name.</returns>
    /// <exception cref="ArgumentNullException">Thrown when <paramref name="outboxTableName"/> is null or empty.</exception>
    public static string GetDDL(string outboxTableName, bool hasBinaryMessagePayload = false)
    {
        if (string.IsNullOrEmpty(outboxTableName))
        {
            throw new ArgumentNullException(outboxTableName, $"You must provide a tablename for the OutBox table");
        }

        return string.Format(hasBinaryMessagePayload ? BinaryOutboxDdl : TextOutboxDdl, outboxTableName);
    }
}
