// <auto-generated />

using GreetingsPorts.EntityGateway;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;

namespace Greetings_MySqlMigrations.Migrations
{
    [DbContext(typeof(GreetingsEntityGateway))]
    [Migration("20210920185059_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.9")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("GreetingsEntities.Greeting", b =>
                {
                    b.Property<int>("_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Recipient_id")
                        .HasColumnType("int");

                    b.HasKey("_id");

                    b.HasIndex("Recipient_id");

                    b.ToTable("Greeting");
                });

            modelBuilder.Entity("GreetingsEntities.Person", b =>
                {
                    b.Property<int>("_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<byte[]>("TimeStamp")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("_id");

                    b.HasAlternateKey("Name");

                    b.ToTable("People");
                });

            modelBuilder.Entity("GreetingsEntities.Greeting", b =>
                {
                    b.HasOne("GreetingsEntities.Person", "Recipient")
                        .WithMany("Greetings")
                        .HasForeignKey("Recipient_id");

                    b.Navigation("Recipient");
                });

            modelBuilder.Entity("GreetingsEntities.Person", b =>
                {
                    b.Navigation("Greetings");
                });
#pragma warning restore 612, 618
        }
    }
}
