// <auto-generated/>
// ─────────────────────────────────────────────────────────────────────────────────────
// PROTOTYPE — hand-written stand-in for the Phase-2 output of
// [BrighterRegistrations(GenerateBuilderExtensions = true)].
//
// In the real design this file is generated INTO Orders.Domain, which then must reference
// Paramore.Brighter.Extensions.DependencyInjection (the documented coupling trade). It lives
// in the host here only so the prototype's Orders.Domain stays core-only.
//
// Method naming is mechanical — Add + user-chosen holder/group name (+ "Registrations") —
// because holders and groups already carry human-chosen names. No regex renaming machinery
// (cf. NServiceBus RegistrationMethodNamePatterns) is needed. Every body is a one-liner
// over AddRegistrations: sugar, never logic.
// ─────────────────────────────────────────────────────────────────────────────────────
#nullable enable

namespace Orders.Domain
{
    public static class OrdersRegistrationsBuilderExtensions
    {
        /// <summary>Registers everything in <see cref="OrdersRegistrations.Catalog"/>.</summary>
        public static global::Paramore.Brighter.Extensions.DependencyInjection.IBrighterBuilder AddOrdersRegistrations(
            this global::Paramore.Brighter.Extensions.DependencyInjection.IBrighterBuilder builder)
            => global::Paramore.Brighter.Extensions.DependencyInjection.BrighterBuilderRegistrationExtensions.AddRegistrations(builder, global::Orders.Domain.OrdersRegistrations.Catalog);

        /// <summary>Registers the [RegistrationGroup("Billing")] group.</summary>
        public static global::Paramore.Brighter.Extensions.DependencyInjection.IBrighterBuilder AddBillingRegistrations(
            this global::Paramore.Brighter.Extensions.DependencyInjection.IBrighterBuilder builder)
            => global::Paramore.Brighter.Extensions.DependencyInjection.BrighterBuilderRegistrationExtensions.AddRegistrations(builder, global::Orders.Domain.OrdersRegistrations.Billing);

        /// <summary>Registers the [RegistrationGroup("Fulfilment")] group.</summary>
        public static global::Paramore.Brighter.Extensions.DependencyInjection.IBrighterBuilder AddFulfilmentRegistrations(
            this global::Paramore.Brighter.Extensions.DependencyInjection.IBrighterBuilder builder)
            => global::Paramore.Brighter.Extensions.DependencyInjection.BrighterBuilderRegistrationExtensions.AddRegistrations(builder, global::Orders.Domain.OrdersRegistrations.Fulfilment);

        /// <summary>Registers the [RegistrationGroup("Urgent")] group.</summary>
        public static global::Paramore.Brighter.Extensions.DependencyInjection.IBrighterBuilder AddUrgentRegistrations(
            this global::Paramore.Brighter.Extensions.DependencyInjection.IBrighterBuilder builder)
            => global::Paramore.Brighter.Extensions.DependencyInjection.BrighterBuilderRegistrationExtensions.AddRegistrations(builder, global::Orders.Domain.OrdersRegistrations.Urgent);
    }
}
