#region Licence

/* The MIT License (MIT)
Copyright © 2014 Ian Cooper <ian_hammond_cooper@yahoo.co.uk>

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE. */

#endregion

using System.Threading.Tasks;

// <auto-generated>
// This file is auto-generated by Paramore.Brighter.Test.Generator
// </auto-generated>

using Paramore.Brighter;

namespace Paramore.Brighter.AWS.Tests;

/// <summary>
/// Default implementation of <see cref="IAmAMessageAssertion"/> that asserts equality of message headers and body.
/// </summary>
public class DefaultMessageAssertion : IAmAMessageAssertion
{
    /// <summary>
    /// Asserts that the actual message matches the expected message by comparing all header properties and body value.
    /// </summary>
    /// <param name="expected">The expected message.</param>
    /// <param name="actual">The actual message to compare.</param>
    public async Task AssertAsync(Message expected, Message actual)
    {
       await Assert.That(actual.Header.MessageType).IsEqualTo(expected.Header.MessageType);
       await Assert.That(actual.Header.ContentType).IsEqualTo(expected.Header.ContentType);
       await Assert.That(actual.Header.CorrelationId).IsEqualTo(expected.Header.CorrelationId);
       await Assert.That(actual.Header.DataSchema).IsEqualTo(expected.Header.DataSchema);
       await Assert.That(actual.Header.MessageId).IsEqualTo(expected.Header.MessageId);
       await Assert.That(actual.Header.PartitionKey).IsEqualTo(expected.Header.PartitionKey);
       await Assert.That(actual.Header.ReplyTo).IsEqualTo(expected.Header.ReplyTo);
       await Assert.That(actual.Header.Subject).IsEqualTo(expected.Header.Subject);
       await Assert.That(actual.Header.SpecVersion).IsEqualTo(expected.Header.SpecVersion);
       await Assert.That(actual.Header.Source).IsEqualTo(expected.Header.Source);
       await Assert.That(actual.Header.Topic).IsEqualTo(expected.Header.Topic);
       await Assert.That(actual.Header.TimeStamp.ToString("yyyy-MM-ddTHH:mm:ss")).IsEqualTo(expected.Header.TimeStamp.ToString("yyyy-MM-ddTHH:mm:ss"));
       await Assert.That(actual.Header.Type).IsEqualTo(expected.Header.Type);
       await Assert.That(actual.Header.HandledCount).IsEqualTo(expected.Header.HandledCount);
       await Assert.That(actual.Header.Delayed).IsEqualTo(System.TimeSpan.Zero);
       await Assert.That(actual.Body.Value).IsEqualTo(expected.Body.Value);
       await Assert.That(actual.Header.TraceParent).IsEqualTo(expected.Header.TraceParent);
       await Assert.That(actual.Header.TraceState).IsEqualTo(expected.Header.TraceState);
       await Assert.That(actual.Header.Baggage).IsEqualTo(expected.Header.Baggage);
    }
}
