#region Licence
/* The MIT License (MIT)
Copyright © 2024 Ian Cooper <ian_hammond_cooper@yahoo.co.uk>

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE. */

#endregion

using System;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Paramore.Brighter.MessagingGateway.RMQ.Async;
using Xunit;

namespace Paramore.Brighter.RMQ.Async.Tests.MessagingGateway.Acceptance;

// Acceptance tests verify actual mTLS connections to Docker RabbitMQ
// These tests run against the actual transport configured in Docker (per ADR #3946)
[Trait("Category", "RabbitMQ")]
[Trait("Category", "MutualTLS")]
[Trait("Requires", "Docker-mTLS")]
public class RmqMutualTlsAcceptanceTests : IDisposable
{
    private readonly string _clientCertPath;
    private const string CertPassword = "test-password";

    public RmqMutualTlsAcceptanceTests()
    {
        // Path to client certificate generated by generate-test-certs.sh
        _clientCertPath = Path.Combine(
            AppDomain.CurrentDomain.BaseDirectory,
            "..",
            "..",
            "..",
            "..",
            "certs",
            "client-cert.pfx");
    }

    public void Dispose()
    {
        // Cleanup if needed
    }

    [Fact]
    public async Task When_connecting_with_client_certificate_can_publish_message_async()
    {
        // Verify certificate exists
        if (!File.Exists(_clientCertPath))
        {
            throw new FileNotFoundException(
                $"Client certificate not found at {_clientCertPath}. " +
                "Run ./tests/generate-test-certs.sh to generate certificates.");
        }

        // Arrange
        var connection = new RmqMessagingGatewayConnection
        {
            AmpqUri = new AmqpUriSpecification(new Uri("amqps://localhost:5671")),
            Exchange = new Exchange("test.mtls.exchange.async"),
            ClientCertificatePath = _clientCertPath,
            ClientCertificatePassword = CertPassword,
            TrustServerSelfSignedCertificate = true  // Trust self-signed certificates in test environment
        };

        // Act
        var producer = new RmqMessageProducer(connection);
        var message = new Message(
            new MessageHeader(Id.Random(), "test.mtls.topic.async", MessageType.MT_EVENT),
            new MessageBody("Test message over mTLS (async)")
        );

        // Assert - Should NOT throw TLS handshake exception
        // Actual TLS handshake occurs when SendAsync() is called
        await producer.SendAsync(message);

        // If we reach here, TLS handshake succeeded
        Assert.True(true);

        // Cleanup
        await producer.DisposeAsync();
    }

    [Fact]
    public async Task When_connecting_with_mtls_can_publish_and_receive_message_async()
    {
        // Verify certificate exists
        if (!File.Exists(_clientCertPath))
        {
            throw new FileNotFoundException(
                $"Client certificate not found at {_clientCertPath}. " +
                "Run ./tests/generate-test-certs.sh to generate certificates.");
        }

        // Arrange
        var queueName = $"test.mtls.queue.async.{Id.Random()}";
        var routingKey = "test.mtls.roundtrip.async";

        var connection = new RmqMessagingGatewayConnection
        {
            AmpqUri = new AmqpUriSpecification(new Uri("amqps://localhost:5671")),
            Exchange = new Exchange("test.mtls.exchange.async"),
            ClientCertificatePath = _clientCertPath,
            ClientCertificatePassword = CertPassword,
            TrustServerSelfSignedCertificate = true  // Trust self-signed certificates in test environment
        };

        // Act - Create consumer first to ensure queue exists and is bound
        var consumer = new RmqMessageConsumer(connection, queueName, routingKey, false);
        consumer.Purge(); // Ensure queue is created and bound before publishing

        // Act - Publish
        var producer = new RmqMessageProducer(connection);
        var sentMessage = new Message(
            new MessageHeader(Id.Random(), routingKey, MessageType.MT_EVENT),
            new MessageBody("Round-trip test over mTLS (async)")
        );
        await producer.SendAsync(sentMessage);

        // Act - Consume
        var receivedMessages = await consumer.ReceiveAsync(TimeSpan.FromSeconds(5));

        // Assert
        Assert.NotEmpty(receivedMessages);
        var receivedMessage = receivedMessages.First();
        Assert.Equal(sentMessage.Id, receivedMessage.Id);
        Assert.Equal(sentMessage.Body.Value, receivedMessage.Body.Value);

        // Cleanup
        await producer.DisposeAsync();
        await consumer.DisposeAsync();
    }
}
