version: '3.1'
services:
  web:
    build: ./GreetingsAdapters
    hostname: greetingsapi
    ports:
      - "5000:5000"
    environment:
      - BRIGHTER_ConnectionStrings__Greetings=server=greetings_db; port=3306; uid=root; pwd=root; database=Greetings
      - BRIGHTER_ConnectionStrings__GreetingsDb=server=greetings_db; port=3306; uid=root; pwd=root
      - ASPNETCORE_ENVIRONMENT=Production
    links:
      - mysql:greetings_db
    depends_on:
      - mysql
      - rabbitmq
  worker:
    build: ./GreetingsWatcher
    hostname: greetingsworker
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    depends_on:
      - rabbitmq
  mysql:
    hostname: greetings_db
    image: mysql
    ports:
      - "3306:3306"
    security_opt:
      - seccomp:unconfined
    volumes:
      - my-db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: "root"
    healthcheck:
      test: mysqladmin ping -h localhost -p$$MYSQL_ROOT_PASSWORD && test '0' -eq $$(ps aux | awk '{print $$11}' | grep -c -e '^mysql$$')
  rabbitmq:
    image: brightercommand/rabbitmq:3.8-management-delay
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq-home:/var/lib/rabbitmq

volumes:
    rabbitmq-home:
      driver: local
    my-db:
      driver: local


