<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>$(BrighterTestTargetFrameworks)</TargetFrameworks>
    <IsPackable>false</IsPackable>
    <OutputType>Exe</OutputType>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../../src/Paramore.Brighter.Archive.Azure/Paramore.Brighter.Archive.Azure.csproj" />
    <ProjectReference Include="../../src/Paramore.Brighter.Locking.Azure/Paramore.Brighter.Locking.Azure.csproj" />
    <ProjectReference Include="..\..\src\Paramore.Brighter.ServiceActivator\Paramore.Brighter.ServiceActivator.csproj" />
    <ProjectReference Include="..\..\src\Paramore.Brighter.MessagingGateway.AzureServiceBus\Paramore.Brighter.MessagingGateway.AzureServiceBus.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Azure.Messaging.ServiceBus" />
    <PackageReference Include="OpenTelemetry.Exporter.InMemory" />
    <PackageReference Include="TUnit" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Binder" />
  </ItemGroup>
</Project>
