using System.Linq;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Testing;
using Microsoft.CodeAnalysis.Testing;
using Paramore.Brighter.Extensions.DependencyInjection;

namespace Paramore.Brighter.SourceGenerators.Tests;

/// <summary>
/// End-to-end "validation" tests: drive the generator through Microsoft.CodeAnalysis.Testing,
/// supply user source, and assert on the generated source against an expected document.
/// </summary>
public class BrighterRegistrationsGeneratorTests
{
    private static CSharpSourceGeneratorTest<BrighterRegistrationsGenerator, DefaultVerifier> MakeTest() =>
        new()
        {
            ReferenceAssemblies = ReferenceAssemblies.Net.Net90,
            TestState =
            {
                AdditionalReferences =
                {
                    MetadataReference.CreateFromFile(typeof(IRequest).Assembly.Location),
                    MetadataReference.CreateFromFile(typeof(IBrighterBuilder).Assembly.Location),
                },
            },
        };

    [Fact]
    public async Task NoBrighterReference_GeneratesAttributesOnly()
    {
        var test = new CSharpSourceGeneratorTest<BrighterRegistrationsGenerator, DefaultVerifier>
        {
            ReferenceAssemblies = ReferenceAssemblies.Net.Net90,
            TestState =
            {
                Sources = { "// no user code" },
            },
        };
        // Post-init output is still emitted; only the per-method registration is skipped.
        test.TestState.GeneratedSources.Add(AttributeFile());

        await test.RunAsync();
    }

    [Fact]
    public async Task SyncHandler_GeneratesRegistration()
    {
        const string userCode = """
            using Paramore.Brighter;
            using Paramore.Brighter.Extensions.DependencyInjection;

            namespace App;

            public class GreetingCommand : Command
            {
                public GreetingCommand() : base(System.Guid.NewGuid()) { }
            }

            public class GreetingHandler : RequestHandler<GreetingCommand>
            {
                public override GreetingCommand Handle(GreetingCommand command) => base.Handle(command);
            }

            public static partial class Registrations
            {
                [BrighterRegistrations]
                public static partial IBrighterBuilder AddFromThisAssembly(this IBrighterBuilder builder);
            }
            """;

        var test = MakeTest();
        test.TestState.Sources.Add(userCode);
        test.TestState.GeneratedSources.Add(AttributeFile());
        test.TestState.GeneratedSources.Add((
            typeof(BrighterRegistrationsGenerator),
            "App_Registrations__AddFromThisAssembly.g.cs",
            """
            // <auto-generated/>
            #nullable enable

            namespace App
            {
                public static partial class Registrations
                {
                    public static partial global::Paramore.Brighter.Extensions.DependencyInjection.IBrighterBuilder AddFromThisAssembly(this global::Paramore.Brighter.Extensions.DependencyInjection.IBrighterBuilder builder)
                    {
                        builder.Handlers(r =>
                        {
                            var registry = (global::Paramore.Brighter.Extensions.DependencyInjection.ServiceCollectionSubscriberRegistry)r;
                            registry.Add(typeof(global::App.GreetingCommand), typeof(global::App.GreetingHandler));
                        });
                        return builder;
                    }
                }
            }

            """));

        await test.RunAsync();
    }

    [Fact]
    public async Task ExcludedType_IsNotRegistered()
    {
        const string userCode = """
            using Paramore.Brighter;
            using Paramore.Brighter.Extensions.DependencyInjection;

            namespace App;

            public class GreetingCommand : Command
            {
                public GreetingCommand() : base(System.Guid.NewGuid()) { }
            }

            [ExcludeFromBrighterRegistration]
            public class GreetingHandler : RequestHandler<GreetingCommand>
            {
                public override GreetingCommand Handle(GreetingCommand command) => base.Handle(command);
            }

            public static partial class Registrations
            {
                [BrighterRegistrations]
                public static partial IBrighterBuilder AddFromThisAssembly(this IBrighterBuilder builder);
            }
            """;

        var test = MakeTest();
        test.TestState.Sources.Add(userCode);
        test.TestState.GeneratedSources.Add(AttributeFile());
        test.TestState.GeneratedSources.Add((
            typeof(BrighterRegistrationsGenerator),
            "App_Registrations__AddFromThisAssembly.g.cs",
            """
            // <auto-generated/>
            #nullable enable

            namespace App
            {
                public static partial class Registrations
                {
                    public static partial global::Paramore.Brighter.Extensions.DependencyInjection.IBrighterBuilder AddFromThisAssembly(this global::Paramore.Brighter.Extensions.DependencyInjection.IBrighterBuilder builder)
                    {
                        return builder;
                    }
                }
            }

            """));

        await test.RunAsync();
    }

    [Fact]
    public async Task NonPartialMethod_ReportsBRGEN001()
    {
        const string userCode = """
            using Paramore.Brighter;
            using Paramore.Brighter.Extensions.DependencyInjection;

            namespace App;

            public static class Registrations
            {
                [BrighterRegistrations]
                public static IBrighterBuilder AddFromThisAssembly(IBrighterBuilder builder) => builder;
            }
            """;

        var test = MakeTest();
        test.TestState.Sources.Add(userCode);
        test.TestState.GeneratedSources.Add(AttributeFile());
        test.TestState.ExpectedDiagnostics.Add(
            DiagnosticResult.CompilerError("BRGEN001").WithSpan(9, 36, 9, 55).WithArguments("AddFromThisAssembly"));

        await test.RunAsync();
    }

    private static (System.Type, string, string) AttributeFile() => (
        typeof(BrighterRegistrationsGenerator),
        "BrighterRegistrationsAttributes.g.cs",
        """
        // <auto-generated/>
        #nullable enable
        namespace Paramore.Brighter
        {
            /// <summary>
            /// Marks a <c>partial</c> method that the Brighter source generator will implement
            /// to register handlers and message mappers discovered in the current compilation.
            /// The method must be <c>static partial</c>, return <see cref="Paramore.Brighter.Extensions.DependencyInjection.IBrighterBuilder"/>,
            /// and take a single <see cref="Paramore.Brighter.Extensions.DependencyInjection.IBrighterBuilder"/> parameter (extension methods supported).
            /// </summary>
            [global::System.AttributeUsage(global::System.AttributeTargets.Method, AllowMultiple = false, Inherited = false)]
            internal sealed class BrighterRegistrationsAttribute : global::System.Attribute
            {
            }

            /// <summary>
            /// Excludes a handler / mapper / transform type from automatic Brighter registration.
            /// </summary>
            [global::System.AttributeUsage(global::System.AttributeTargets.Class, AllowMultiple = false, Inherited = false)]
            internal sealed class ExcludeFromBrighterRegistrationAttribute : global::System.Attribute
            {
            }
        }
        """);
}
