using System.Linq;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Testing;
using Microsoft.CodeAnalysis.Testing;
using Paramore.Brighter.Extensions.DependencyInjection;

namespace Paramore.Brighter.SourceGenerators.Tests;

/// <summary>
/// End-to-end "validation" tests: drive the generator through Microsoft.CodeAnalysis.Testing,
/// supply user source, and assert on the generated source against an expected document.
/// </summary>
public class BrighterRegistrationsGeneratorTests
{
    private static CSharpSourceGeneratorTest<BrighterRegistrationsGenerator, DefaultVerifier> MakeTest() =>
        new()
        {
            ReferenceAssemblies = ReferenceAssemblies.Net.Net90,
            TestState =
            {
                AdditionalReferences =
                {
                    MetadataReference.CreateFromFile(typeof(IRequest).Assembly.Location),
                    MetadataReference.CreateFromFile(typeof(IBrighterBuilder).Assembly.Location),
                },
            },
        };

    [Fact]
    public async Task NoBrighterReference_GeneratesAttributesOnly()
    {
        var test = new CSharpSourceGeneratorTest<BrighterRegistrationsGenerator, DefaultVerifier>
        {
            ReferenceAssemblies = ReferenceAssemblies.Net.Net90,
            TestState =
            {
                Sources = { "// no user code" },
            },
        };
        // Post-init output is still emitted; only the per-method registration is skipped.
        test.TestState.GeneratedSources.Add(AttributeFile());

        await test.RunAsync();
    }

    [Fact]
    public async Task SyncHandler_GeneratesRegistration()
    {
        const string userCode = """
            using Paramore.Brighter;
            using Paramore.Brighter.Extensions.DependencyInjection;

            namespace App;

            public class GreetingCommand : Command
            {
                public GreetingCommand() : base(System.Guid.NewGuid()) { }
            }

            public class GreetingHandler : RequestHandler<GreetingCommand>
            {
                public override GreetingCommand Handle(GreetingCommand command) => base.Handle(command);
            }

            public static partial class Registrations
            {
                [BrighterRegistrations]
                public static partial IBrighterBuilder AddFromThisAssembly(this IBrighterBuilder builder);
            }
            """;

        var test = MakeTest();
        test.TestState.Sources.Add(userCode);
        test.TestState.GeneratedSources.Add(AttributeFile());
        test.TestState.GeneratedSources.Add((
            typeof(BrighterRegistrationsGenerator),
            "App_Registrations_6a7651d4__AddFromThisAssembly.g.cs",
            """
            // <auto-generated/>
            #nullable enable

            namespace App
            {
                public static partial class Registrations
                {
                    public static partial global::Paramore.Brighter.Extensions.DependencyInjection.IBrighterBuilder AddFromThisAssembly(this global::Paramore.Brighter.Extensions.DependencyInjection.IBrighterBuilder builder)
                    {
                        builder.Handlers(r =>
                        {
                            r.Register<global::App.GreetingCommand, global::App.GreetingHandler>();
                        });
                        return builder;
                    }
                }
            }

            """));

        await test.RunAsync();
    }

    [Fact]
    public async Task ExcludedType_IsNotRegistered()
    {
        const string userCode = """
            using Paramore.Brighter;
            using Paramore.Brighter.Extensions.DependencyInjection;

            namespace App;

            public class GreetingCommand : Command
            {
                public GreetingCommand() : base(System.Guid.NewGuid()) { }
            }

            [ExcludeFromBrighterRegistration]
            public class GreetingHandler : RequestHandler<GreetingCommand>
            {
                public override GreetingCommand Handle(GreetingCommand command) => base.Handle(command);
            }

            public static partial class Registrations
            {
                [BrighterRegistrations]
                public static partial IBrighterBuilder AddFromThisAssembly(this IBrighterBuilder builder);
            }
            """;

        var test = MakeTest();
        test.TestState.Sources.Add(userCode);
        test.TestState.GeneratedSources.Add(AttributeFile());
        test.TestState.GeneratedSources.Add((
            typeof(BrighterRegistrationsGenerator),
            "App_Registrations_6a7651d4__AddFromThisAssembly.g.cs",
            """
            // <auto-generated/>
            #nullable enable

            namespace App
            {
                public static partial class Registrations
                {
                    public static partial global::Paramore.Brighter.Extensions.DependencyInjection.IBrighterBuilder AddFromThisAssembly(this global::Paramore.Brighter.Extensions.DependencyInjection.IBrighterBuilder builder)
                    {
                        return builder;
                    }
                }
            }

            """));

        await test.RunAsync();
    }

    [Fact]
    public async Task AsyncHandler_GeneratesRegisterAsync()
    {
        const string userCode = """
            using Paramore.Brighter;
            using Paramore.Brighter.Extensions.DependencyInjection;

            namespace App;

            public class GreetingCommand : Command
            {
                public GreetingCommand() : base(System.Guid.NewGuid()) { }
            }

            public class GreetingHandler : RequestHandlerAsync<GreetingCommand>
            {
            }

            public static partial class Registrations
            {
                [BrighterRegistrations]
                public static partial IBrighterBuilder AddFromThisAssembly(this IBrighterBuilder builder);
            }
            """;

        var test = MakeTest();
        test.TestState.Sources.Add(userCode);
        test.TestState.GeneratedSources.Add(AttributeFile());
        test.TestState.GeneratedSources.Add((
            typeof(BrighterRegistrationsGenerator),
            "App_Registrations_6a7651d4__AddFromThisAssembly.g.cs",
            """
            // <auto-generated/>
            #nullable enable

            namespace App
            {
                public static partial class Registrations
                {
                    public static partial global::Paramore.Brighter.Extensions.DependencyInjection.IBrighterBuilder AddFromThisAssembly(this global::Paramore.Brighter.Extensions.DependencyInjection.IBrighterBuilder builder)
                    {
                        builder.AsyncHandlers(r =>
                        {
                            r.RegisterAsync<global::App.GreetingCommand, global::App.GreetingHandler>();
                        });
                        return builder;
                    }
                }
            }

            """));

        await test.RunAsync();
    }

    [Fact]
    public async Task MapperAndAsyncMapperAndTransform_AreAllDiscovered()
    {
        const string userCode = """
            using System;
            using Paramore.Brighter;
            using Paramore.Brighter.Extensions.DependencyInjection;

            namespace App;

            public class GreetingEvent : Event { public GreetingEvent() : base(System.Guid.NewGuid()) { } }

            public class GreetingMapper : IAmAMessageMapper<GreetingEvent>
            {
                public IRequestContext? Context { get; set; }
                public Message MapToMessage(GreetingEvent request, Publication publication) => new();
                public GreetingEvent MapToRequest(Message message) => new();
            }

            public class GreetingMapperAsync : IAmAMessageMapperAsync<GreetingEvent>
            {
                public IRequestContext? Context { get; set; }
                public System.Threading.Tasks.Task<Message> MapToMessageAsync(GreetingEvent request, Publication publication, System.Threading.CancellationToken ct = default) => System.Threading.Tasks.Task.FromResult(new Message());
                public System.Threading.Tasks.Task<GreetingEvent> MapToRequestAsync(Message message, System.Threading.CancellationToken ct = default) => System.Threading.Tasks.Task.FromResult(new GreetingEvent());
            }

            public class NoOp : IAmAMessageTransform
            {
                public IRequestContext? Context { get; set; }
                public void InitializeWrapFromAttributeParams(params object?[] init) { }
                public void InitializeUnwrapFromAttributeParams(params object?[] init) { }
                public Message Wrap(Message m, Publication p) => m;
                public Message Unwrap(Message m) => m;
                public void Dispose() { }
            }

            public static partial class Registrations
            {
                [BrighterRegistrations]
                public static partial IBrighterBuilder AddFromThisAssembly(this IBrighterBuilder builder);
            }
            """;

        var test = MakeTest();
        test.TestState.Sources.Add(userCode);
        test.TestState.GeneratedSources.Add(AttributeFile());
        test.TestState.GeneratedSources.Add((
            typeof(BrighterRegistrationsGenerator),
            "App_Registrations_6a7651d4__AddFromThisAssembly.g.cs",
            """
            // <auto-generated/>
            #nullable enable

            namespace App
            {
                public static partial class Registrations
                {
                    public static partial global::Paramore.Brighter.Extensions.DependencyInjection.IBrighterBuilder AddFromThisAssembly(this global::Paramore.Brighter.Extensions.DependencyInjection.IBrighterBuilder builder)
                    {
                        builder.MapperRegistry(r =>
                        {
                            r.Add(typeof(global::App.GreetingEvent), typeof(global::App.GreetingMapper));
                            r.AddAsync(typeof(global::App.GreetingEvent), typeof(global::App.GreetingMapperAsync));
                        });
                        global::Paramore.Brighter.Extensions.DependencyInjection.BrighterBuilderExtensions.Transforms(builder, r =>
                        {
                            r.Add(typeof(global::App.NoOp));
                        });
                        return builder;
                    }
                }
            }

            """));

        await test.RunAsync();
    }

    [Fact]
    public async Task PartialHandler_IsRegisteredOnce()
    {
        const string partA = """
            using Paramore.Brighter;
            using Paramore.Brighter.Extensions.DependencyInjection;

            namespace App;

            public class GreetingCommand : Command
            {
                public GreetingCommand() : base(System.Guid.NewGuid()) { }
            }

            public partial class SplitHandler : RequestHandler<GreetingCommand>
            {
                public override GreetingCommand Handle(GreetingCommand command) => base.Handle(command);
            }

            public static partial class Registrations
            {
                [BrighterRegistrations]
                public static partial IBrighterBuilder AddFromThisAssembly(this IBrighterBuilder builder);
            }
            """;

        const string partB = """
            namespace App;

            public partial class SplitHandler
            {
                public void Helper() { }
            }
            """;

        var test = MakeTest();
        test.TestState.Sources.Add(partA);
        test.TestState.Sources.Add(partB);
        test.TestState.GeneratedSources.Add(AttributeFile());
        test.TestState.GeneratedSources.Add((
            typeof(BrighterRegistrationsGenerator),
            "App_Registrations_6a7651d4__AddFromThisAssembly.g.cs",
            """
            // <auto-generated/>
            #nullable enable

            namespace App
            {
                public static partial class Registrations
                {
                    public static partial global::Paramore.Brighter.Extensions.DependencyInjection.IBrighterBuilder AddFromThisAssembly(this global::Paramore.Brighter.Extensions.DependencyInjection.IBrighterBuilder builder)
                    {
                        builder.Handlers(r =>
                        {
                            r.Register<global::App.GreetingCommand, global::App.SplitHandler>();
                        });
                        return builder;
                    }
                }
            }

            """));

        await test.RunAsync();
    }

    [Fact]
    public async Task AbstractAndPrivateNestedHandlers_AreFilteredOut()
    {
        const string userCode = """
            using Paramore.Brighter;
            using Paramore.Brighter.Extensions.DependencyInjection;

            namespace App;

            public class GreetingCommand : Command
            {
                public GreetingCommand() : base(System.Guid.NewGuid()) { }
            }

            public abstract class AbstractHandler : RequestHandler<GreetingCommand>
            {
            }

            internal class Outer
            {
                private class PrivateNested : RequestHandler<GreetingCommand>
                {
                    public override GreetingCommand Handle(GreetingCommand command) => base.Handle(command);
                }
            }

            public static partial class Registrations
            {
                [BrighterRegistrations]
                public static partial IBrighterBuilder AddFromThisAssembly(this IBrighterBuilder builder);
            }
            """;

        var test = MakeTest();
        test.TestState.Sources.Add(userCode);
        test.TestState.GeneratedSources.Add(AttributeFile());
        test.TestState.GeneratedSources.Add((
            typeof(BrighterRegistrationsGenerator),
            "App_Registrations_6a7651d4__AddFromThisAssembly.g.cs",
            """
            // <auto-generated/>
            #nullable enable

            namespace App
            {
                public static partial class Registrations
                {
                    public static partial global::Paramore.Brighter.Extensions.DependencyInjection.IBrighterBuilder AddFromThisAssembly(this global::Paramore.Brighter.Extensions.DependencyInjection.IBrighterBuilder builder)
                    {
                        return builder;
                    }
                }
            }

            """));

        await test.RunAsync();
    }

    [Fact]
    public async Task GenericMapper_ReportsBRGEN005()
    {
        const string userCode = """
            using Paramore.Brighter;
            using Paramore.Brighter.Extensions.DependencyInjection;

            namespace App;

            public class GreetingEvent : Event { public GreetingEvent() : base(System.Guid.NewGuid()) { } }

            public class OpenMapper<T> : IAmAMessageMapper<GreetingEvent>
            {
                public IRequestContext? Context { get; set; }
                public Message MapToMessage(GreetingEvent request, Publication publication) => new();
                public GreetingEvent MapToRequest(Message message) => new();
            }

            public static partial class Registrations
            {
                [BrighterRegistrations]
                public static partial IBrighterBuilder AddFromThisAssembly(this IBrighterBuilder builder);
            }
            """;

        var test = MakeTest();
        test.TestState.Sources.Add(userCode);
        test.TestState.GeneratedSources.Add(AttributeFile());
        test.TestState.GeneratedSources.Add((
            typeof(BrighterRegistrationsGenerator),
            "App_Registrations_6a7651d4__AddFromThisAssembly.g.cs",
            """
            // <auto-generated/>
            #nullable enable

            namespace App
            {
                public static partial class Registrations
                {
                    public static partial global::Paramore.Brighter.Extensions.DependencyInjection.IBrighterBuilder AddFromThisAssembly(this global::Paramore.Brighter.Extensions.DependencyInjection.IBrighterBuilder builder)
                    {
                        return builder;
                    }
                }
            }

            """));
        test.TestState.ExpectedDiagnostics.Add(
            DiagnosticResult.CompilerWarning("BRGEN005").WithSpan(8, 14, 8, 24).WithArguments("global::App.OpenMapper<T>"));

        await test.RunAsync();
    }

    [Fact]
    public async Task NonStaticMethod_ReportsBRGEN002()
    {
        const string userCode = """
            using Paramore.Brighter;
            using Paramore.Brighter.Extensions.DependencyInjection;

            namespace App;

            public partial class Registrations
            {
                [BrighterRegistrations]
                public partial IBrighterBuilder AddFromThisAssembly(IBrighterBuilder builder);
            }
            """;

        var test = MakeTest();
        test.TestState.Sources.Add(userCode);
        test.TestState.GeneratedSources.Add(AttributeFile());
        test.TestState.ExpectedDiagnostics.Add(
            DiagnosticResult.CompilerError("BRGEN002").WithSpan(9, 37, 9, 56).WithArguments("AddFromThisAssembly"));
        // The C# compiler will also complain that the partial method has no implementation;
        // we don't care about its exact diagnostics here.
        test.CompilerDiagnostics = CompilerDiagnostics.None;

        await test.RunAsync();
    }

    [Fact]
    public async Task WrongReturnType_ReportsBRGEN003()
    {
        const string userCode = """
            using Paramore.Brighter;
            using Paramore.Brighter.Extensions.DependencyInjection;

            namespace App;

            public static partial class Registrations
            {
                [BrighterRegistrations]
                public static partial void AddFromThisAssembly(IBrighterBuilder builder);
            }
            """;

        var test = MakeTest();
        test.TestState.Sources.Add(userCode);
        test.TestState.GeneratedSources.Add(AttributeFile());
        test.TestState.ExpectedDiagnostics.Add(
            DiagnosticResult.CompilerError("BRGEN003").WithSpan(9, 32, 9, 51).WithArguments("AddFromThisAssembly"));
        test.CompilerDiagnostics = CompilerDiagnostics.None;

        await test.RunAsync();
    }

    [Fact]
    public async Task WrongSignature_ReportsBRGEN004()
    {
        const string userCode = """
            using Paramore.Brighter;
            using Paramore.Brighter.Extensions.DependencyInjection;

            namespace App;

            public static partial class Registrations
            {
                [BrighterRegistrations]
                public static partial IBrighterBuilder AddFromThisAssembly(IBrighterBuilder builder, int extra);
            }
            """;

        var test = MakeTest();
        test.TestState.Sources.Add(userCode);
        test.TestState.GeneratedSources.Add(AttributeFile());
        test.TestState.ExpectedDiagnostics.Add(
            DiagnosticResult.CompilerError("BRGEN004").WithSpan(9, 44, 9, 63).WithArguments("AddFromThisAssembly"));
        test.CompilerDiagnostics = CompilerDiagnostics.None;

        await test.RunAsync();
    }

    [Fact]
    public async Task NonPartialMethod_ReportsBRGEN001()
    {
        const string userCode = """
            using Paramore.Brighter;
            using Paramore.Brighter.Extensions.DependencyInjection;

            namespace App;

            public static class Registrations
            {
                [BrighterRegistrations]
                public static IBrighterBuilder AddFromThisAssembly(IBrighterBuilder builder) => builder;
            }
            """;

        var test = MakeTest();
        test.TestState.Sources.Add(userCode);
        test.TestState.GeneratedSources.Add(AttributeFile());
        test.TestState.ExpectedDiagnostics.Add(
            DiagnosticResult.CompilerError("BRGEN001").WithSpan(9, 36, 9, 55).WithArguments("AddFromThisAssembly"));

        await test.RunAsync();
    }

    private static (System.Type, string, string) AttributeFile() => (
        typeof(BrighterRegistrationsGenerator),
        "BrighterRegistrationsAttributes.g.cs",
        """
        // <auto-generated/>
        #nullable enable
        namespace Paramore.Brighter
        {
            /// <summary>
            /// Marks a <c>partial</c> method that the Brighter source generator will implement
            /// to register handlers and message mappers discovered in the current compilation.
            /// The method must be <c>static partial</c>, return <see cref="Paramore.Brighter.Extensions.DependencyInjection.IBrighterBuilder"/>,
            /// and take a single <see cref="Paramore.Brighter.Extensions.DependencyInjection.IBrighterBuilder"/> parameter (extension methods supported).
            /// </summary>
            [global::System.AttributeUsage(global::System.AttributeTargets.Method, AllowMultiple = false, Inherited = false)]
            internal sealed class BrighterRegistrationsAttribute : global::System.Attribute
            {
            }

            /// <summary>
            /// Excludes a handler / mapper / transform type from automatic Brighter registration.
            /// </summary>
            [global::System.AttributeUsage(global::System.AttributeTargets.Class, AllowMultiple = false, Inherited = false)]
            internal sealed class ExcludeFromBrighterRegistrationAttribute : global::System.Attribute
            {
            }
        }
        """);
}
