using Paramore.Brighter.SourceGenerators;
using Paramore.Brighter.SourceGenerators.Model;

namespace Paramore.Brighter.SourceGenerators.Tests;

public class RegistrationWriterTests
{
    private static RegistrationModel EmptyModel(
        EquatableArray<HandlerEntry>? handlers = null,
        EquatableArray<HandlerEntry>? asyncHandlers = null,
        EquatableArray<MapperEntry>? mappers = null,
        EquatableArray<MapperEntry>? asyncMappers = null,
        EquatableArray<string>? transforms = null,
        string? @namespace = "MyApp",
        bool containingTypeIsStatic = true,
        bool isExtensionMethod = true) =>
        new(
            new MethodTarget(
                Namespace: @namespace,
                ContainingTypeAccessibility: "public",
                ContainingTypeName: "Registrations",
                ContainingTypeIsStatic: containingTypeIsStatic,
                MethodAccessibility: "public",
                MethodName: "AddFromThisAssembly",
                ReturnTypeFullyQualified: "global::Paramore.Brighter.Extensions.DependencyInjection.IBrighterBuilder",
                ParameterTypeFullyQualified: "global::Paramore.Brighter.Extensions.DependencyInjection.IBrighterBuilder",
                ParameterName: "builder",
                IsExtensionMethod: isExtensionMethod,
                HintName: "MyApp_Registrations__AddFromThisAssembly.g.cs"),
            handlers ?? EquatableArray<HandlerEntry>.Empty,
            asyncHandlers ?? EquatableArray<HandlerEntry>.Empty,
            mappers ?? EquatableArray<MapperEntry>.Empty,
            asyncMappers ?? EquatableArray<MapperEntry>.Empty,
            transforms ?? EquatableArray<string>.Empty);

    [Fact]
    public void EmitsGeneratedBannerAndGeneratedCodeAttribute()
    {
        var output = RegistrationWriter.Write(EmptyModel());

        Assert.Contains("// <auto-generated>", output);
        Assert.Contains("This code was generated by the Brighter source generator.", output);
        Assert.Contains("[global::System.CodeDom.Compiler.GeneratedCode(\"Paramore.Brighter.SourceGenerators\", ", output);
    }

    [Fact]
    public void EmptyModel_EmitsScaffoldAndReturnsBuilder()
    {
        var output = RegistrationWriter.Write(EmptyModel());

        Assert.Contains("namespace MyApp", output);
        Assert.Contains("public static partial class Registrations", output);
        Assert.Contains("public static partial global::Paramore.Brighter.Extensions.DependencyInjection.IBrighterBuilder AddFromThisAssembly(this global::Paramore.Brighter.Extensions.DependencyInjection.IBrighterBuilder builder)", output);
        Assert.Contains("return builder;", output);
        Assert.DoesNotContain(".Handlers(", output);
        Assert.DoesNotContain(".Transforms(", output);
        // MapperRegistry is always emitted so the default message mapper is registered, matching
        // AutoFromAssemblies even when no mappers are discovered.
        Assert.Contains("builder.MapperRegistry(r =>", output);
    }

    [Fact]
    public void ClosedHandler_UsesGenericRegisterAndOmitsImplementationCast()
    {
        var model = EmptyModel(handlers: new EquatableArray<HandlerEntry>(new[]
        {
            new HandlerEntry("global::MyApp.GreetingCommand", "global::MyApp.GreetingCommandHandler", IsOpenGeneric: false)
        }));

        var output = RegistrationWriter.Write(model);

        Assert.Contains("builder.Handlers(r =>", output);
        Assert.Contains("r.Register<global::MyApp.GreetingCommand, global::MyApp.GreetingCommandHandler>();", output);
        Assert.DoesNotContain("ServiceCollectionSubscriberRegistry", output);
    }

    [Fact]
    public void OpenGenericHandler_EmitsEnsureHandlerIsRegistered()
    {
        var model = EmptyModel(handlers: new EquatableArray<HandlerEntry>(new[]
        {
            new HandlerEntry(string.Empty, "global::MyApp.PolicyHandler<>", IsOpenGeneric: true)
        }));

        var output = RegistrationWriter.Write(model);

        Assert.Contains("var registry = r as global::Paramore.Brighter.Extensions.DependencyInjection.ServiceCollectionSubscriberRegistry ?? throw new global::System.InvalidOperationException(", output);
        Assert.Contains("registry.EnsureHandlerIsRegistered(typeof(global::MyApp.PolicyHandler<>));", output);
    }

    [Fact]
    public void MixedClosedAndOpenHandlers_EmitsCastOnlyOnce()
    {
        var model = EmptyModel(handlers: new EquatableArray<HandlerEntry>(new[]
        {
            new HandlerEntry("global::MyApp.GreetingCommand", "global::MyApp.GreetingCommandHandler", IsOpenGeneric: false),
            new HandlerEntry(string.Empty, "global::MyApp.PolicyHandler<>", IsOpenGeneric: true),
        }));

        var output = RegistrationWriter.Write(model);

        Assert.Contains("r.Register<global::MyApp.GreetingCommand, global::MyApp.GreetingCommandHandler>();", output);
        Assert.Contains("registry.EnsureHandlerIsRegistered(typeof(global::MyApp.PolicyHandler<>));", output);
        // The registry is resolved exactly once, even with multiple open generics.
        var registryResolves = output.Split(new[] { "var registry =" }, System.StringSplitOptions.None).Length - 1;
        Assert.Equal(1, registryResolves);
    }

    [Fact]
    public void AsyncHandlerOnly_UsesAsyncHandlersCallback()
    {
        var model = EmptyModel(asyncHandlers: new EquatableArray<HandlerEntry>(new[]
        {
            new HandlerEntry("global::MyApp.GreetingCommand", "global::MyApp.GreetingCommandHandlerAsync", IsOpenGeneric: false)
        }));

        var output = RegistrationWriter.Write(model);

        Assert.Contains("builder.AsyncHandlers(r =>", output);
        Assert.DoesNotContain("builder.Handlers(r =>", output);
    }

    [Fact]
    public void Mappers_EmitsAddAndAddAsyncCalls()
    {
        var model = EmptyModel(
            mappers: new EquatableArray<MapperEntry>(new[]
            {
                new MapperEntry("global::MyApp.GreetingEvent", "global::MyApp.GreetingEventMapper")
            }),
            asyncMappers: new EquatableArray<MapperEntry>(new[]
            {
                new MapperEntry("global::MyApp.GreetingEvent", "global::MyApp.GreetingEventMapperAsync")
            }));

        var output = RegistrationWriter.Write(model);

        Assert.Contains("builder.MapperRegistry(r =>", output);
        Assert.Contains("r.Add(typeof(global::MyApp.GreetingEvent), typeof(global::MyApp.GreetingEventMapper));", output);
        Assert.Contains("r.AddAsync(typeof(global::MyApp.GreetingEvent), typeof(global::MyApp.GreetingEventMapperAsync));", output);
    }

    [Fact]
    public void Transforms_EmitsTransformsCallback()
    {
        var model = EmptyModel(transforms: new EquatableArray<string>(new[]
        {
            "global::MyApp.NoOpTransformer"
        }));

        var output = RegistrationWriter.Write(model);

        Assert.Contains("global::Paramore.Brighter.Extensions.DependencyInjection.BrighterBuilderExtensions.Transforms(builder, r =>", output);
        Assert.Contains("r.Add(typeof(global::MyApp.NoOpTransformer));", output);
    }

    [Fact]
    public void GlobalNamespace_OmitsNamespaceWrapper()
    {
        var model = EmptyModel(@namespace: null);

        var output = RegistrationWriter.Write(model);

        Assert.DoesNotContain("namespace ", output);
        Assert.Contains("public static partial class Registrations", output);
    }

    [Fact]
    public void NonStaticContainingType_EmitsPartialClassWithoutStatic()
    {
        var model = EmptyModel(containingTypeIsStatic: false, isExtensionMethod: false);

        var output = RegistrationWriter.Write(model);

        Assert.Contains("public partial class Registrations", output);
        Assert.DoesNotContain("static partial class", output);
        Assert.DoesNotContain("this global::Paramore.Brighter", output);
    }
}
