#region Licence

/* The MIT License (MIT)
Copyright © 2014 Ian Cooper <ian_hammond_cooper@yahoo.co.uk>

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE. */

#endregion

// <auto-generated>
// This file is auto-generated by Paramore.Brighter.Test.Generator
// </auto-generated>

using System;
using System.Net.Mime;
using System.Collections.Generic;

using Paramore.Brighter.Observability;

namespace Paramore.Brighter.RMQ.Async.Tests;

/// <summary>
/// Default implementation of <see cref="IAmAMessageFactory"/> that creates messages with randomly generated test data.
/// </summary>
public class DefaultMessageFactory : IAmAMessageFactory
{
    /// <summary>
    /// Gets the list of messages that have been created by this factory.
    /// </summary>
    public List<Message> CreatedMessages { get; } = new();

    /// <summary>
    /// Creates a new message with the specified configuration.
    /// </summary>
    /// <param name="configuration">The message configuration specifying header values and body content. If null, uses default values.</param>
    /// <returns>A new <see cref="Message"/> instance with the specified configuration.</returns>
    public Message Create(MessageConfiguration? configuration = null)
    {
        configuration ??= new MessageConfiguration();
        var messageHeader = new MessageHeader(
            messageId: configuration.MessageId,
            topic: configuration.Topic,
            messageType: configuration.MessageType,
            source: configuration.Source,
            type: configuration.Type,
            timeStamp: configuration.TimeStamp,
            correlationId: configuration.CorrelationId,
            replyTo: configuration.ReplyTo,
            contentType: configuration.ContentType,
            partitionKey: configuration.PartitionKey,
            subject: configuration.Subject,
            dataSchema: configuration.DataSchema,
            delayed: configuration.Delayed,
            traceParent: configuration.TraceParent,
            traceState: configuration.TraceState,
            baggage: configuration.Baggage,
            workflowId: configuration.WorkflowId,
            jobId: configuration.JobId)
        {
            SpecVersion = configuration.SpecVersion, 
            Bag = configuration.Bag
        };

        var message = new Message(messageHeader, new MessageBody(configuration.Body));

        CreatedMessages.Add(message);

        return message;
    }
}
