#region Licence

/* The MIT License (MIT)
Copyright © 2014 Ian Cooper <ian_hammond_cooper@yahoo.co.uk>

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE. */

#endregion

// <auto-generated>
// This file is auto-generated by Paramore.Brighter.Test.Generator
// </auto-generated>

using System;
using System.Collections.Generic;
using System.Net.Mime;
using System.Text;

using Paramore.Brighter;
using Paramore.Brighter.Observability;

namespace Paramore.Brighter.RMQ.Async.Tests;

/// <summary>
/// Factory for creating message instances with optional timestamps.
/// </summary>
public interface IAmAMessageFactory
{
    /// <summary>
    /// Gets the list of messages that have been created by this factory.
    /// </summary>
    List<Message> CreatedMessages { get; }

    Message Create(MessageConfiguration? configuration = null);
}

public class MessageConfiguration
{
    public Dictionary<string, object> Bag { get; set; } = new()
    {
        ["header1"] = Uuid.NewAsString(),
        ["header2"] = Uuid.NewAsString(),
        ["header3"] = Uuid.NewAsString(),
        ["header4"] = Uuid.NewAsString(),
        ["header5"] = Uuid.NewAsString()
    };

  public Baggage Baggage { get; set; } = new();
  
  public ContentType ContentType { get; set; } = new ContentType(MediaTypeNames.Text.Plain);

  public Id CorrelationId { get; set; } = Id.Random();

  public Uri? DataSchema { get; set; } = new Uri($"https://{Uuid.New():N}.test");
        
  public string? DataRef { get; set; } = Uuid.NewAsString();
        
  public TimeSpan? Delayed { get; set; }
        
  public Id? JobId { get; set; } = Id.Random();

  public Id? MessageId { get; set; } = Id.Random();

  public MessageType MessageType { get; set; } = MessageType.MT_EVENT;

  public PartitionKey PartitionKey { get; set; } = new PartitionKey(Uuid.NewAsString());
        
  public RoutingKey? ReplyTo { get; set; } = new RoutingKey(Uuid.NewAsString());

  public string? Subject { get; set; } = Uuid.NewAsString();

  public string? SpecVersion { get; set; } = "1.0";
        
  public Uri? Source { get; set; } = new Uri(Uuid.NewAsString(), UriKind.Relative);

  public RoutingKey Topic { get; set; } = new RoutingKey(Uuid.NewAsString());

  public DateTimeOffset TimeStamp { get; set; } = DateTimeOffset.UtcNow;
        
  public TraceParent? TraceParent { get; set; } = new TraceParent(Uuid.NewAsString());

  public TraceState? TraceState { get; set; } = new TraceState(Uuid.NewAsString());

  public CloudEventsType Type { get; set; } = new CloudEventsType(Uuid.NewAsString());
        
  public Id? WorkflowId { get; set; } = Id.Random();

  public byte[] Body { get; set; } = Encoding.UTF8.GetBytes(Uuid.NewAsString());
}

