version: '3.1'
services:
 dynamo:
    image: dwmkerr/dynamodb
    command: "-inMemory"
    hostname: dynamo
    volumes:
      - dynamodb:/data
    ports:
      - "8000:8000"
 rabbitmq:
    image: brightercommand/rabbitmq:3.8-management-delay
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq-home:/var/lib/rabbitmq

volumes:
    rabbitmq-home:
      driver: local
    dynamodb:
      driver: local
 
