#region Licence
/* The MIT License (MIT)
Copyright © 2026 Ian Cooper <ian_hammond_cooper@yahoo.co.uk>

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE. */
#endregion

using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace Paramore.Brighter.SourceGenerators;

/// <summary>
/// Emits a partial implementation of a user-declared method that registers Brighter handlers,
/// message mappers and transforms from the current compilation. Replaces runtime
/// <c>AutoFromAssemblies</c> reflection scanning with compile-time generated registrations.
/// </summary>
/// <remarks>
/// The generator follows a three-stage pipeline:
/// <list type="bullet">
///   <item><see cref="SemanticModelReader"/> turns Roslyn symbols into a <see cref="Model.RegistrationModel"/>.</item>
///   <item><see cref="RegistrationWriter"/> turns the model into source text (pure function).</item>
///   <item>This class wires those stages into the incremental pipeline.</item>
/// </list>
/// Separating read from write keeps the writer unit-testable without a Compilation.
/// </remarks>
[Generator(LanguageNames.CSharp)]
public sealed class BrighterRegistrationsGenerator : IIncrementalGenerator
{
    private const string AttributeName = "Paramore.Brighter.BrighterRegistrationsAttribute";

    private const string AttributeSource = """
        // <auto-generated/>
        #nullable enable
        namespace Paramore.Brighter
        {
            /// <summary>
            /// Marks a <c>partial</c> method that the Brighter source generator will implement
            /// to register handlers and message mappers discovered in the current compilation.
            /// The method must be <c>static partial</c>, return <see cref="Paramore.Brighter.Extensions.DependencyInjection.IBrighterBuilder"/>,
            /// and take a single <see cref="Paramore.Brighter.Extensions.DependencyInjection.IBrighterBuilder"/> parameter (extension methods supported).
            /// </summary>
            [global::System.AttributeUsage(global::System.AttributeTargets.Method, AllowMultiple = false, Inherited = false)]
            internal sealed class BrighterRegistrationsAttribute : global::System.Attribute
            {
            }

            /// <summary>
            /// Excludes a handler / mapper / transform type from automatic Brighter registration.
            /// </summary>
            [global::System.AttributeUsage(global::System.AttributeTargets.Class, AllowMultiple = false, Inherited = false)]
            internal sealed class ExcludeFromBrighterRegistrationAttribute : global::System.Attribute
            {
            }
        }
        """;

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterPostInitializationOutput(ctx =>
            ctx.AddSource("BrighterRegistrationsAttributes.g.cs", SourceText.From(AttributeSource, Encoding.UTF8)));

        var methodTargets = context.SyntaxProvider
            .ForAttributeWithMetadataName(
                AttributeName,
                predicate: static (node, _) => node is MethodDeclarationSyntax,
                transform: static (ctx, _) => (IMethodSymbol)ctx.TargetSymbol)
            .Where(static m => m is not null)
            .Collect();

        var combined = methodTargets.Combine(context.CompilationProvider);

        context.RegisterSourceOutput(combined, static (spc, pair) =>
        {
            var methods = pair.Left;
            var compilation = pair.Right;

            if (methods.IsDefaultOrEmpty)
                return;

            var symbols = MarkerSymbols.Resolve(compilation);
            if (!symbols.IsValid)
                return;

            foreach (var method in methods)
            {
                var result = SemanticModelReader.TryBuildModel(method, compilation, symbols);
                if (!result.Success)
                {
                    if (result.Diagnostic is not null)
                        spc.ReportDiagnostic(result.Diagnostic);
                    continue;
                }

                var model = result.Model!;
                spc.AddSource(model.HintName, SourceText.From(RegistrationWriter.Write(model), Encoding.UTF8));
            }
        });
    }
}
