#region Licence
/* The MIT License (MIT)
Copyright © 2026 Ian Cooper <ian_hammond_cooper@yahoo.co.uk>

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE. */
#endregion

namespace Paramore.Brighter.SourceGenerators;

/// <summary>
/// Shared markers for emitted source: the "this file was generated" banner and the
/// <c>[System.CodeDom.Compiler.GeneratedCode]</c> stamp. Centralised so every generated file is
/// labelled consistently and the tool version is read from a single place. Modelled on the
/// equivalent helpers in the ASP.NET Core source generators.
/// </summary>
public static class GeneratedSource
{
    /// <summary>The tool name recorded in <c>[GeneratedCode]</c>.</summary>
    public const string ToolName = "Paramore.Brighter.SourceGenerators";

    /// <summary>The generator assembly version recorded in <c>[GeneratedCode]</c>.</summary>
    public static string ToolVersion { get; } =
        typeof(GeneratedSource).Assembly.GetName().Version?.ToString() ?? "1.0.0.0";

    /// <summary>
    /// The auto-generated file banner. Does not include a <c>#nullable</c> directive — each emitter
    /// adds its own — so the banner can sit ahead of whatever the file needs next.
    /// </summary>
    public static string Header { get; } =
        """
        //------------------------------------------------------------------------------
        // <auto-generated>
        //     This code was generated by the Brighter source generator.
        //
        //     Changes to this file may cause incorrect behavior and will be lost if
        //     the code is regenerated.
        // </auto-generated>
        //------------------------------------------------------------------------------
        """;

    /// <summary>
    /// The <c>[System.CodeDom.Compiler.GeneratedCode(...)]</c> attribute, fully qualified so it can
    /// be emitted into any namespace without a using directive.
    /// </summary>
    public static string GeneratedCodeAttribute { get; } =
        $"[global::System.CodeDom.Compiler.GeneratedCode(\"{ToolName}\", \"{ToolVersion}\")]";
}
