#region Licence
/* The MIT License (MIT)
Copyright © 2026 Ian Cooper <ian_hammond_cooper@yahoo.co.uk>

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE. */
#endregion

using System.Text;
using Paramore.Brighter.SourceGenerators.Model;

namespace Paramore.Brighter.SourceGenerators;

/// <summary>
/// Pure function that turns a <see cref="RegistrationModel"/> into the C# source for the
/// partial method implementation. Holds no Roslyn references, so it can be unit-tested
/// without constructing a Compilation.
/// </summary>
public static class RegistrationWriter
{
    public static string Write(RegistrationModel model)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();

        var hasNamespace = !string.IsNullOrEmpty(model.Namespace);
        if (hasNamespace)
        {
            sb.Append("namespace ").Append(model.Namespace).AppendLine();
            sb.AppendLine("{");
        }

        WriteContainingTypeOpen(sb, model);
        WriteMethodSignature(sb, model);

        WriteHandlers(sb, model.ParameterName, model.Handlers, isAsync: false);
        WriteHandlers(sb, model.ParameterName, model.AsyncHandlers, isAsync: true);
        WriteMappers(sb, model.ParameterName, model.Mappers, model.AsyncMappers);
        WriteTransforms(sb, model.ParameterName, model.Transforms);

        sb.Append("            return ").Append(model.ParameterName).AppendLine(";");
        sb.AppendLine("        }");
        sb.AppendLine("    }");

        if (hasNamespace)
            sb.AppendLine("}");

        return sb.ToString();
    }

    private static void WriteContainingTypeOpen(StringBuilder sb, RegistrationModel model)
    {
        var typeKeyword = (model.ContainingTypeIsStatic, model.IsPartial) switch
        {
            (true, true) => "static partial class",
            (true, false) => "static class",
            (false, true) => "partial class",
            (false, false) => "class",
        };
        sb.Append("    ")
            .Append(model.ContainingTypeAccessibility)
            .Append(' ')
            .Append(typeKeyword)
            .Append(' ')
            .AppendLine(model.ContainingTypeName);
        sb.AppendLine("    {");
    }

    private static void WriteMethodSignature(StringBuilder sb, RegistrationModel model)
    {
        sb.Append("        ").Append(model.MethodAccessibility).Append(" static ");
        if (model.IsPartial)
            sb.Append("partial ");
        sb.Append(model.ReturnTypeFullyQualified).Append(' ').Append(model.MethodName).Append('(');
        if (model.IsExtensionMethod)
            sb.Append("this ");
        sb.Append(model.ParameterTypeFullyQualified).Append(' ').Append(model.ParameterName);
        sb.AppendLine(")");
        sb.AppendLine("        {");
    }

    private static void WriteHandlers(
        StringBuilder sb,
        string paramName,
        EquatableArray<HandlerEntry> entries,
        bool isAsync)
    {
        if (entries.Count == 0)
            return;

        var callbackMethod = isAsync ? "AsyncHandlers" : "Handlers";
        var registerMethod = isAsync ? "RegisterAsync" : "Register";
        var hasOpenGeneric = false;
        foreach (var entry in entries)
        {
            if (entry.IsOpenGeneric) { hasOpenGeneric = true; break; }
        }

        sb.Append("            ").Append(paramName).Append('.').Append(callbackMethod).AppendLine("(r =>");
        sb.AppendLine("            {");

        // For closed-generic handlers, use the strongly-typed Register<TRequest, TImpl>() method
        // available on the public interface — no implementation cast needed.
        foreach (var entry in entries)
        {
            if (entry.IsOpenGeneric) continue;
            sb.Append("                r.").Append(registerMethod).Append('<')
                .Append(entry.RequestTypeFullyQualified).Append(", ")
                .Append(entry.HandlerTypeFullyQualified)
                .AppendLine(">();");
        }

        // Open-generic handlers need EnsureHandlerIsRegistered, which only exists on the DI
        // extension's concrete ServiceCollectionSubscriberRegistry. Emit the cast only when at
        // least one open generic is present, so the common case stays interface-only.
        if (hasOpenGeneric)
        {
            sb.AppendLine("                var registry = (global::Paramore.Brighter.Extensions.DependencyInjection.ServiceCollectionSubscriberRegistry)r;");
            foreach (var entry in entries)
            {
                if (!entry.IsOpenGeneric) continue;
                sb.Append("                registry.EnsureHandlerIsRegistered(typeof(")
                    .Append(entry.HandlerTypeFullyQualified)
                    .AppendLine("));");
            }
        }

        sb.AppendLine("            });");
    }

    private static void WriteMappers(
        StringBuilder sb,
        string paramName,
        EquatableArray<MapperEntry> sync,
        EquatableArray<MapperEntry> async)
    {
        if (sync.Count == 0 && async.Count == 0)
            return;

        sb.Append("            ").Append(paramName).AppendLine(".MapperRegistry(r =>");
        sb.AppendLine("            {");

        foreach (var entry in sync)
        {
            sb.Append("                r.Add(typeof(")
                .Append(entry.RequestTypeFullyQualified)
                .Append("), typeof(")
                .Append(entry.MapperTypeFullyQualified)
                .AppendLine("));");
        }

        foreach (var entry in async)
        {
            sb.Append("                r.AddAsync(typeof(")
                .Append(entry.RequestTypeFullyQualified)
                .Append("), typeof(")
                .Append(entry.MapperTypeFullyQualified)
                .AppendLine("));");
        }

        sb.AppendLine("            });");
    }

    private static void WriteTransforms(
        StringBuilder sb,
        string paramName,
        EquatableArray<string> transforms)
    {
        if (transforms.Count == 0)
            return;

        // Transforms is an extension method on IBrighterBuilder; call statically so the
        // generated source doesn't depend on a `using` being added by the consumer.
        sb.Append("            global::Paramore.Brighter.Extensions.DependencyInjection.BrighterBuilderExtensions.Transforms(")
            .Append(paramName)
            .AppendLine(", r =>");
        sb.AppendLine("            {");

        foreach (var transform in transforms)
        {
            sb.Append("                r.Add(typeof(")
                .Append(transform)
                .AppendLine("));");
        }

        sb.AppendLine("            });");
    }
}
