#region Licence

/* The MIT License (MIT)
Copyright © 2014 Ian Cooper <ian_hammond_cooper@yahoo.co.uk>

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE. */

#endregion

// <auto-generated>
// This file is auto-generated by Paramore.Brighter.Test.Generator
// </auto-generated>

using System;

namespace Paramore.Brighter.MSSQL.Tests;

/// <summary>
/// Factory for creating message instances with optional timestamps.
/// </summary>
public interface IAmAMessageFactory
{
    /// <summary>
    /// Creates a new message instance.
    /// </summary>
    /// <param name="timestamp">The timestamp for the message. If null, the current time will be used.</param>
    /// <returns>A new <see cref="Message"/> instance.</returns>
    Message Create(DateTimeOffset? timestamp = null);
}
