#region Licence

/* The MIT License (MIT)
Copyright © 2014 Ian Cooper <ian_hammond_cooper@yahoo.co.uk>

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE. */

#endregion

// <auto-generated>
// This file is auto-generated by Paramore.Brighter.Test.Generator
// </auto-generated>
using System;
using System.Collections.Generic;
using System.Net.Mime;
using System.Text;

using Paramore.Brighter;
using Paramore.Brighter.Observability;

namespace Paramore.Brighter.MySQL.Tests;

/// <summary>
/// Builder interface for creating test messages with customizable header values and body content.
/// </summary>
public interface IAmAMessageBuilder
{
    /// <summary>
    /// Sets the bag of additional header values.
    /// </summary>
    /// <param name="bag">The dictionary of additional header values.</param>
    /// <returns>The builder instance for method chaining.</returns>
    IAmAMessageBuilder SetBag(Dictionary<string, object> bag);

    /// <summary>
    /// Sets the baggage for distributed tracing context propagation.
    /// </summary>
    /// <param name="baggage">The baggage for distributed tracing.</param>
    /// <returns>The builder instance for method chaining.</returns>
    IAmAMessageBuilder SetBaggage(Baggage baggage);

    /// <summary>
    /// Sets the content type of the message body.
    /// </summary>
    /// <param name="contentType">The content type of the message.</param>
    /// <returns>The builder instance for method chaining.</returns>
    IAmAMessageBuilder SetContentType(ContentType contentType);

    /// <summary>
    /// Sets the correlation identifier for tracking related messages.
    /// </summary>
    /// <param name="correlationId">The correlation identifier.</param>
    /// <returns>The builder instance for method chaining.</returns>
    IAmAMessageBuilder SetCorrelationId(Id correlationId);

    /// <summary>
    /// Sets the URI identifying the schema of the data in the message body.
    /// </summary>
    /// <param name="dataSchema">The data schema URI.</param>
    /// <returns>The builder instance for method chaining.</returns>
    IAmAMessageBuilder SetDataSchema(Uri? dataSchema);

    /// <summary>
    /// Sets a reference to external data.
    /// </summary>
    /// <param name="dataRef">The external data reference.</param>
    /// <returns>The builder instance for method chaining.</returns>
    IAmAMessageBuilder SetDataRef(string? dataRef);

    /// <summary>
    /// Sets the delay before the message should be processed.
    /// </summary>
    /// <param name="delayed">The delay timespan.</param>
    /// <returns>The builder instance for method chaining.</returns>
    IAmAMessageBuilder SetDelayed(TimeSpan? delayed);

    /// <summary>
    /// Sets the job identifier for workflow tracking.
    /// </summary>
    /// <param name="jobId">The job identifier.</param>
    /// <returns>The builder instance for method chaining.</returns>
    IAmAMessageBuilder SetJobId(Id? jobId);

    /// <summary>
    /// Sets the unique message identifier.
    /// </summary>
    /// <param name="messageId">The message identifier.</param>
    /// <returns>The builder instance for method chaining.</returns>
    IAmAMessageBuilder SetMessageId(Id? messageId);

    /// <summary>
    /// Sets the message type (Event, Command, etc.).
    /// </summary>
    /// <param name="messageType">The message type.</param>
    /// <returns>The builder instance for method chaining.</returns>
    IAmAMessageBuilder SetMessageType(MessageType messageType);

    /// <summary>
    /// Sets the partition key for message routing.
    /// </summary>
    /// <param name="partitionKey">The partition key.</param>
    /// <returns>The builder instance for method chaining.</returns>
    IAmAMessageBuilder SetPartitionKey(PartitionKey partitionKey);

    /// <summary>
    /// Sets the reply-to routing key for response messages.
    /// </summary>
    /// <param name="replyTo">The reply-to routing key.</param>
    /// <returns>The builder instance for method chaining.</returns>
    IAmAMessageBuilder SetReplyTo(RoutingKey? replyTo);

    /// <summary>
    /// Sets the subject or title of the message.
    /// </summary>
    /// <param name="subject">The message subject.</param>
    /// <returns>The builder instance for method chaining.</returns>
    IAmAMessageBuilder SetSubject(string? subject);

    /// <summary>
    /// Sets the CloudEvents specification version.
    /// </summary>
    /// <param name="specVersion">The CloudEvents spec version.</param>
    /// <returns>The builder instance for method chaining.</returns>
    IAmAMessageBuilder SetSpecVersion(string? specVersion);

    /// <summary>
    /// Sets the URI identifying the source of the message.
    /// </summary>
    /// <param name="source">The message source URI.</param>
    /// <returns>The builder instance for method chaining.</returns>
    IAmAMessageBuilder SetSource(Uri? source);

    /// <summary>
    /// Sets the topic routing key for message publishing.
    /// </summary>
    /// <param name="topic">The topic routing key.</param>
    /// <returns>The builder instance for method chaining.</returns>
    IAmAMessageBuilder SetTopic(RoutingKey topic);

    /// <summary>
    /// Sets the timestamp when the message was created.
    /// </summary>
    /// <param name="timeStamp">The message timestamp.</param>
    /// <returns>The builder instance for method chaining.</returns>
    IAmAMessageBuilder SetTimeStamp(DateTimeOffset timeStamp);

    /// <summary>
    /// Sets the W3C trace parent for distributed tracing.
    /// </summary>
    /// <param name="traceParent">The W3C trace parent.</param>
    /// <returns>The builder instance for method chaining.</returns>
    IAmAMessageBuilder SetTraceParent(TraceParent? traceParent);

    /// <summary>
    /// Sets the W3C trace state for vendor-specific tracing information.
    /// </summary>
    /// <param name="traceState">The W3C trace state.</param>
    /// <returns>The builder instance for method chaining.</returns>
    IAmAMessageBuilder SetTraceState(TraceState? traceState);

    /// <summary>
    /// Sets the CloudEvents type describing the message content.
    /// </summary>
    /// <param name="type">The CloudEvents type.</param>
    /// <returns>The builder instance for method chaining.</returns>
    IAmAMessageBuilder SetType(CloudEventsType type);

    /// <summary>
    /// Sets the workflow identifier for process tracking.
    /// </summary>
    /// <param name="workflowId">The workflow identifier.</param>
    /// <returns>The builder instance for method chaining.</returns>
    IAmAMessageBuilder SetWorkflowId(Id? workflowId);

    /// <summary>
    /// Sets the message body content as a byte array.
    /// </summary>
    /// <param name="body">The message body content.</param>
    /// <returns>The builder instance for method chaining.</returns>
    IAmAMessageBuilder SetBody(byte[] body);

    /// <summary>
    /// Builds and returns the configured message.
    /// </summary>
    /// <returns>The constructed message with all configured properties.</returns>
    Message Build();
}

